### ISSUE TITLE
wifi-ifaces parameters

### ISSUE THREAD

**Issue by cholin** [freifunk-berlin/firmware#108]
Some setups do alter `beacon_int` and `basic_rate` for wifi-ifaces for speed improvements (see http://wiki.freifunk.net/Berlin:Standorte:Emmauskirche#Feintuning). Should we do this as well and if yes which values would you recommend? Just as a reminder for adhoc interfaces we already set `mcast_rate` (see #34).

**Comment by cholin** [comment]
I close this because I think for the moment we do have others problems than optimising.

**Comment by booo** [comment]
Well we can use milestones to prioritize issues but I'm fine with closing this one anyway.
