### ISSUE TITLE
patch for wrt54gl

### ISSUE THREAD

**Issue by mdik** [freifunk-berlin/firmware#120]
Hi,

I heard there is a patch. I'd be interested in trying it out. Otherwise, I'd be interested to swap 2 Linksys WRT54GL for 1 more thoroughly supported wifi router.

Thanks in advance,

Malte

**Comment by booo** [comment]
If you think this is still somehow relevant please add a wiki page and link this issue. I'm closing this one now because there is now interest from the developer community to support this device and nearly no interest from the user side.
