### ISSUE TITLE
Should a node in the network check the selected gateway for connectivity to the upstream network?

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#130]
At the moment only the gateway itself checks if the uplink (e.g. over the wan port) works. The node uses the dynamic gateway plugin from olsr to check for an 0.0.0.0 HNA. If it's possible to ping the configured node from the dynamic gateway plugin over the ffvpn interface the node sends HNA messages to the other nodes in the network. They can use it as uplink to the internet.

Some questions we should discuss:
- Can a node trust the gateway about the uplink? 
- Can a gateway detect a proper working uplink/wan port (e.g. complex policy routing database makes this hard)?
- Can we use existing tools like dynamic gateway plugin or gw-check
- Is the current tool (dynamic gateway plugin) ipv6 ready?

**Comment by cholin** [comment]
I would clsoe this for now because in olsrd this is not possible.
