### ISSUE TITLE
private access point feature does not work on single ip dhcp setups

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#143]
The current implementation of the private access point feature does not work on setups where the uplink dhcp server serves only one ip address. The router will get an ip address via the wan port. Clients in the private network don't receive an ip address because the pool of ip addresses is already empty.

This is for example the case if you configure your Kabel Deutschland modem to be a layer 2 bridge. The 
speedtouch I use offers a similar option but I am not sure if the problem exists there too.

If we want to support "all" use cases we have to add a nated second network for the private access point.  I do not understand why we need a private access point and want to increase complexity if there is an uplink router that in most cases has a wifi too.

**Comment by cholin** [comment]
I had the feeling in some discussion that there firmware developers who do not like the feature at all. Do we want to put effort in this to fix it or do we want to remove it because of time and complexity reasons?

**Comment by andrenarchy** [comment]
It's not on my priority list so I won't have time to fix it.

**Comment by geirkairam** [comment]
i think people who want to have an private access point can configure this via Administration > Network > Wifi. however, we should offer some documention, how to do that

**Comment by booo** [comment]
I suggest we don't remove the feature before we had a discussion on the mailing list. Some users are quite happy with this (half-broken) feature.

**Comment by sarumpaet** [comment]
I +1 the idea behind the feature in general but I agree that it's a hassle to support (differences in setup for Kabel/DHCP and DSL/PPPoE, etc.). Perhaps some LuCI package for this exists already? Otherwise docs, as geirkairam suggested.

The way the feature is now is basically broken (it won't work with DSL modems on the WAN port nor with cable modems afaics?) and should better be disabled or get a BIG warning notice.

**Comment by sarumpaet** [comment]
For the record, http://lists.berlin.freifunk.net/pipermail/berlin/2015-March/027677.html is basically a howto for setting up the private AP with NAT and a DHCP server.

**Comment by niccokunzmann** [comment]
I would also vote for removing it since it can be created manually.

**Comment by SvenRoederer** [comment]
will be obsolte ehwn merging https://github.com/freifunk-berlin/firmware-packages/pull/107

**Comment by bobster-galore** [comment]
I documented forwarding of private wlan and @sarumpaet 's proposal here https://wiki.freifunk.net/Berlin:erweiterte_Konfiguration . But I'm unsure where to link it, to https://wiki.freifunk.net/Berlin:Firmware ?

**Comment by booo** [comment]
Private AP was removed from the wizard.
