### ISSUE TITLE
frei.funk should resolve to an ipv6 ip

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#166]
At the moment the frei.funk domain name works only for ipv4. It should work for ipv6 as well.

**Comment by cholin** [comment]
The [OpenWRT wiki](http://wiki.openwrt.org/doc/uci/dhcp#custom_domain) mentions ipv6 is not supported for domains. But this seems outdated. An entry with the ULA-ipv6 address should be sufficient to create a local aaaa record entry:

```
config 'frei_funk_ipv6'
	option 'name' 'frei.funk'
	option 'ip'   'fda0:2e79:a57d:1::1'
```

This results in the following:

```
$ host frei.funk
frei.funk has address 10.36.0.225
frei.funk has IPv6 address fda0:2e79:a57d:1::1
```

I think we should integrate this into the wizard.
