### ISSUE TITLE
Tagged+Untagged auf dem selben Port (AR8327N)

### ISSUE THREAD

**Issue by faust2k** [freifunk-berlin/firmware#167]
Vielleicht könnten wir ja diesen Patch in unsere Firmware vorzeitig backporten:
https://dev.openwrt.org/changeset/42653

Schön dass dieser Bug nach Jahren nun endlich geschlossen wurde. Habs eben auf nem WDR3600 mit aktuellen Chaos Calmer Snapshot getestet und klappte prima (sollte also auch den WDR4300 und 4900 betreffen).

**Comment by cholin** [comment]
Ich fänds schön wenn wir das backporten könnten, da der WDR4900 auf vielen MABB Standorten zum Einsatz kommt und hier schon Workarounds in der Konfiguration wegen dem Bug zum Einsatz kommen müssen.

**Comment by booo** [comment]
Der entsprechende Patch lässt sich nicht mehr anwenden. Ich verstehe leider zu wenig vom Code um den sinnvoll einzupflegen. Vielleicht kann sich das nochmal wer angucken?

**Comment by booo** [comment]
Sollte mit dem Update auf chaos-calmer teil der Firmware sein. Ich schließe das Ticket daher.
