### ISSUE TITLE
Menu "Freifunk" is confusing

### ISSUE THREAD

**Issue by monic2001** [freifunk-berlin/firmware#174]
Wording in Menu under "Freifunk" main topic is inconsistent to Freifunk Assistent ...
Proposal, as mentioned for assistent ... in following order 

"Freifunk Einstellungen"
- Grundeinstellung -> "Standortdaten" 
-- this should be splittet from "Profil" and "Profil (Expertenmodus)"
- Kontakt -> "Kontaktdaten"
- "Freifunk Netzwerk" (Step 2/3/4 from Freifunk Assistent) I didn't found any of those settings in the menu?
- "Indexseite" (I didn't exactly get what this is (a Splashpage, where I can put HTML?)

**Comment by sarumpaet** [comment]
Das kommt, weil das Freifunk-Menü aus dem luci-mod-freifunk-Package kommt. Das Thema ist auf dem Radar; wird vermutlich darauf hinauslaufen, dass wir den Berliner Assistenten zu einer Art luci-mod-freifunk-berlin oder sowas ausbauen.
