### ISSUE TITLE
5GHz adhoc interfaces fail to start on outdoor channels

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#181]
Adhoc interfaces currently fail to start on outdoor (DFS!) channels. For example, the following wireless config fails on a NanoStation M5:
```
config wifi-device 'radio0'
	option type 'mac80211'
	option channel '136'
	option path 'pci0000:00/0000:00:00.0'
	option disabled '0'
	option country 'DE'
	option doth '1'
	option hwmode '11an'
	option diversity '1'
	option htmode 'HT20'
	option txpower '15'

config wifi-iface
	option network 'wireless0'
	option device 'radio0'
	option bssid '12:36:CA:FF:EE:EE'
	option ssid 'intern-ch136.freifunk.net'
	option mcast_rate '12000'
	option mode 'adhoc'
	option ifname 'wlan0-adhoc-5'
```

It works if the channel is set to an indoor channel, e.g., channel 36.

**Comment by andrenarchy** [comment]
I chatted with nbd a while ago and the situation is pretty clear: there'll be no DFS with adhoc in ath9k.

As discussed at the firmware hackathon, we can re-include (and perhaps update) @stargieg's [patch](https://github.com/stargieg/firmware/blob/master/patches/001-package-mac80211-regdb.patch) which modifies country 00. Users who know what they're doing can then use country code 00, e.g., in backbone installations or in order to avoid the TPC-related TX power reduction (see the DE section [here](http://git.openwrt.org/?p=14.07/openwrt.git;a=blob;f=package/kernel/mac80211/files/regdb.txt;h=3d1593014aa62caa23114b71c1cd3fa11497103c;hb=HEAD#l255)).

**Comment by lynxis** [comment]
@andrenarchy it looks to me: this is a won't fix resolution. Adhoc on outdoor channels aren't allowed. Right? (please re-open the issue if not. ;)

**Comment by SvenRoederer** [comment]
Anyone knows about the situation for 802.11s on outdoor-channels?

**Comment by bobster-galore** [comment]
ff Wiesbaden goes 802.11s, they might have outdoor equipment.
https://www.wiesbaden.freifunk.net/2017/05/23/umstellung-ibss-auf-80211s.html
https://lists.berlin.freifunk.net/pipermail/berlin/2017-May/035779.html
