### ISSUE TITLE
WLAN speed on TL WR1043ND V1 low

### ISSUE THREAD

**Issue by ces92** [freifunk-berlin/firmware#182]
I had a look about the WLAN speed of the router and it has around 900 Kbit/s. Is this normal with the new firmware?

**Comment by cholin** [comment]
Well we need more information about this. Is the wifi spectrum maybe jammed? Maybe you can provide us with more information like a wifi scan (see https://wireless.wiki.kernel.org/en/users/Documentation/iw#scanning)

**Comment by andrenarchy** [comment]
The TL-WR1043 is known for its buggy wifi chip, see, e.g., [here](https://dev.openwrt.org/ticket/11862). I also had bad performance with this model for years and nbd told me that this particular chip is buggy.

@ces92 I fear we won't be able to fix this issue. If you want you can flash plain openwrt and check if the issue also exists there (trunk and barrier breaker could be tested).

Personally, I switched to a TL-WDR3600 which performs nicely with openwrt (and the freifunk firmware).

**Comment by cholin** [comment]
I would close this issue because of known instability of the wifi chip if that is ok for @ces92 .

**Comment by ces92** [comment]
its ok
