### ISSUE TITLE
Memory leak in olsrd6

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#190]
see http://olsr.org/bugs/view.php?id=48 and https://github.com/freifunk-berlin/router-configs/commit/2271092fc940ffd6e7465f136e7dd874284367e7

I'm creating this issue here as well so we don't forget about it. ;)

**Comment by cholin** [comment]
What is the status with this issue?

**Comment by booo** [comment]
The issue and corresponding solution needs some testing: https://github.com/freifunk-berlin/firmware/pull/192

**Comment by cholin** [comment]
We could test [v5.4.1](https://github.com/openwrt/packages/commit/1b0bd008387d929f536cd6330bc3ee3168244e32) of `collectd` or add a cronjob to restart `luci_statistics` every 30 minutes as a hotfix.
