### ISSUE TITLE
no space left - after initial flashing of wrt841nd v9 (Firmware Berlin (kathleen 0.0.0, based OpenWRT r42554)

### ISSUE THREAD

**Issue by research7** [freifunk-berlin/firmware#191]
Any hints on how to resolve this (description below)?
Thanks!

Firmware: Firmware Berlin (kathleen 0.0.0, based OpenWRT r42554) (downloaded yesterday)
I cannot update certain settings in the web interface, i.e. these updates wont be saved even though
a successful commit was claimed.
For example I attempted to add my geolocation to the basic settings, but I cannot save these.
Neither can I add a wifi access point or change settings for the existing interfaces.
At least I could enable ssh access.
Write attempts to anything other than /tmp were not successful due to "no space left" errors.

This is a "df -h" output:
Filesystem                Size      Used Available Use% Mounted on
rootfs                  320.0K    264.0K     56.0K  83% /
/dev/root                 2.8M      2.8M         0 100% /rom
tmpfs                    14.3M    728.0K     13.5M   5% /tmp
/dev/mtdblock3          320.0K    264.0K     56.0K  83% /overlay
overlayfs:/overlay      320.0K    264.0K     56.0K  83% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by booo** [comment]
We can't do much about this and **I** don't want to do much about it. **I** suggest you buy proper hardware with at least 8MB of flash memory.

You can try to find some packages that are superfluous and we can remove them if it makes sense.

**Comment by research7** [comment]
Thanks for the reply.
Well, according to the "df -h" output I posted above there is 13.5MB free memory. 
Hmm? Where's my mistake?

I do have a  wrt841nd v9 model and downloaded the recommended firmware from
freifunk-berlin.

**Comment by booo** [comment]
13.5MB on the temporary file sysstem. Would you save configuration on a temporary file system?

I don't the you did something wrong. It's just too small...

**Comment by research7** [comment]
I agree, that saving important data on temp fs is not a great idea. but, I assumed that 
this could maybe be solved by sort of repartitioning or whatever ... 

I'll look at your suggestion about finding superfluous packages.

Is there a way to file a bug to the firmware-berlin distribution site?
I think it might be useful to tell people before downloading and flashing 
to check the memory available on the router. That would also avoid bug reports here.

Thanks!

**Comment by booo** [comment]
I don't think you can repartition. You can find more on the flash layout etc. [here](http://wiki.openwrt.org/doc/techref/flash.layout).

At some point we merged a pull request for the ssp library that was somehow superfluous. @lgierth what do you think?

The dnsmasq package can maybe be substituted by the odhcpcd package completly. We have to check if odhcpcd can handle all the dns stuff we use.

Code for the website is here: https://github.com/freifunk-berlin/berlin.freifunk.net
Code for the config registration is here: https://github.com/freifunk-berlin/nipap-wizard

**Comment by cholin** [comment]
If you can provide me the hardware for a couple of days I may can look into this issue. Don't know if next wednesday (07.01) is a regular freifunk meeting in the cbase but we could for instance try to meet us there.

**Comment by andrenarchy** [comment]
@cholin: yes, we meet @ c-base on wednesday (07.01.).

**Comment by research7** [comment]
Thanks, for the links and help offers!
I won't be able to stop by at c-base tomorrow. But at least I could make some progress
in this issue. The things I found and changed:

Findings
--
* The wrt841n(d)v9 has only 4MB. The good news is that this is still sufficient for the kathleen firmware.

* The initial settings have debug logging enabled. I think, this led to the full device.
* I flashed the firmware anew and immediately turned all logging to warning or error. And, now have enough memory for configuring the router. 

In addition, I erased some profiles in /etc/config, which gives me 24% free space
on / (well, only 76k).

Summary and Questions
--
So, the extensive logging in debug mode rendered the device unusable in first place.
Maybe, turn the default logging down for machines with lesser memory?
(Is there a way to limit the log buffer size? I cannot adjust the value in luci System->Logging.)

And, what else could be done to save space?
Especially along the lines of superfluous packages and reduced logging?

Thanks a lot!

**Comment by cholin** [comment]
Logging should not consume any space because it will be saved in-memory (not even tmpfs see http://wiki.openwrt.org/doc/howto/log.essentials). I tried to free some space for devices with limited memory (see #203) On a 841n v8 I had 96KB left without these changes and with it 144KB.

**Comment by mkiesel** [comment]
Perhaps I understand this wrong, but isn't the configuration stored in the overlay? `/dev/mtdblock3 320.0K /overlay`. mtdblock3 is 320K, and removing packages from rootfs (mtdblock2) will not achieve much here...? Looking into /overlay, I don't think there is much space for maneuvering apart from removing the unneeded Freifunk profiles, and these don't amount to much.

Concerning the change in free space you saw, that might be due to the JFFS2 garbage collector or something.

If that's right and repartitioning (to allocate more space to mtd3) isn't possible, I guess there are limited options (perhaps keeping the overlay in RAM and 'committing' as a tar.bz2 file to mtd3, but then again JFFS2 already compresses)...

**Comment by cholin** [comment]
If you strip the kernel or reduce the squashfs size (remove packages from **rom** for instance) you end up with a bigger jffs2 partition (see http://wiki.openwrt.org/doc/techref/flash.layout). This is what I did with #203.

**Comment by mkiesel** [comment]
Thanks for the pointers and your changes. That's really a tight fit then...
For me, currently /overlay is a 320K JFFS2 partition with allegedly 260K used and 60K free space (as per "df"). Nothing can get written to it though ("No space left on device" even for a touch). I guess the garbage collector has seized up or something. Total filesize is only 30K ("du -b"). As a tar.bz2, it's merely 12K.
But I guess getting another router is really it...

**Comment by booo** [comment]
@mkiesel you tested cholins build?

**Comment by mkiesel** [comment]
@booo, sorry, no; are the 48K gains for SSP removal only or with all the packages mentioned removed? I prepared my WRT841N for return already.
There's some discussion concerning very small JFFS2 partitions here: https://forum.openwrt.org/viewtopic.php?id=4039 . If that info (of 2006...) is still correct and I'm not mistaken, three erase blocks (3x64K) of free space are needed for JFFS2 to work properly. Posting 14 in that thread mentions a tmpfs solution similar to what I've been suggesting in my first post here.

**Comment by research7** [comment]
@cholin, thanks a lot for your patch above (https://github.com/freifunk-berlin/firmware/issues/203)!!!
I applied the suggested changes to master, build the image, flashed, and things work fine now!
**One minor addition** 
in order to make the Freifunkassitent work I had to scp profile_berlin to /etc/config

**Space after configuration**
Filesystem                Size      Used Available Use% Mounted on
rootfs                  384.0K    236.0K    148.0K  61% /
/dev/root                 2.5M      2.5M         0 100% /rom
tmpfs                    14.3M    176.0K     14.2M   1% /tmp
/dev/mtdblock3          384.0K    236.0K    148.0K  61% /overlay
overlayfs:/overlay      384.0K    236.0K    148.0K  61% /
tmpfs                   512.0K         0    512.0K   0% /dev

**Comment by booo** [comment]
Problem should be solved with the latest commits on master.
