### ISSUE TITLE
suggestions for the Developer section in README.md

### ISSUE THREAD

**Issue by research7** [freifunk-berlin/firmware#209]
Maybe add the following to the Developer section:

* Be aware to spend a few hours waiting for the entire build.
* keep the build machine connected to the internet for downloads and repo cloning.
* have more than 10GB to spare for the build (mine consumed 9.5 GB)

**Comment by booo** [comment]
@research7 can you create a pull request and add the information?

You can use the -j <parallel builds> option speed up the build process.

Maybe we can add some links to the openwrt wiki?

**Comment by cholin** [comment]
#210 is merged. Can we close this now?

**Comment by booo** [comment]
Yes, we can.
