### ISSUE TITLE
OpenVPN MTU issues with KD (and possibly other providers)

### ISSUE THREAD

**Issue by sarumpaet** [freifunk-berlin/firmware#226]
The default MTU size for OpenVPN doesn't work with some providers/modem configurations, see http://lists.berlin.freifunk.net/pipermail/berlin/2015-February/027280.html and other postings. OpenVPN provides the "mtu-test" option that is supposed to be a flexible fix for this, at the cost of some additional set-up time. Opinions?

**Comment by andrenarchy** [comment]
Maybe these users can test THW Option first?

**Comment by shony666** [comment]
On 20/02/15 19:00, André Gaul wrote:
>
> Maybe these users can test THW Option first?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freifunk-berlin/firmware/issues/226#issuecomment-75288064>.
>
just tell me how
KD ipV6 nonbridged default KD router here and 1043 with VPN for FF

-- 
10.31..08

**Comment by lynxis** [comment]
The mtu discovery works. But testing is even better.
@andrenarchy do we have a testing openvpn server for this?

**Comment by basros** [comment]
A new vpn03 server (vpn03c) has been installed a few months ago. If vpn03-admins don't have time to configure it as additional productive server, it could be used for testing purposes. 
Ask @booo for access

**Comment by booo** [comment]
Has somebody tested the mtu-test/discovery option? @lynxis ?

**Comment by sarumpaet** [comment]
mtu-test unfortunately really only tests (and outputs the result to the log but doesn't change anything).

**Comment by sarumpaet** [comment]
MTU set to 1300 by default in https://github.com/freifunk-berlin/firmware-packages/commit/1820c73c815a7da50e7ddd4931d4497d7c2ebd79 / kathleen 0.1.2.
