### ISSUE TITLE
[firmware] we don't check returncode of the imagebuilder

### ISSUE THREAD

**Issue by lynxis** [freifunk-berlin/firmware#228]
If one profile (e.g. ubnt) fails, the imagebuilder doesn't fail in all cases.
We need to check the return code for every imagebuilder's build.

**Comment by lynxis** [comment]
It's a little bit strange. On my local machine firmware-berlin fails, but on buildbot doesn't.
Any ideas?

**Comment by cholin** [comment]
Maybe `-jX` related? Did you try it without jobs parameter?

**Comment by lynxis** [comment]
@cholin can you try out the branch lynxis/fix-unreported-imagebuilder-fail ?

**Comment by lynxis** [comment]
-jX doesn't change anything on my build host. I'm building by hand.

**Comment by cholin** [comment]
Doesn't work here either. Besides lots of `Ignoring feed 'routing' - index missing` I get `Makefile:1227: recipe for target 'modules' failed`. For a full ouput see [here](http://paste.debian.net/hidden/95443aa2/).

**Comment by lynxis** [comment]
Try a complete clean - `make clean` as well as `cd openwrt; make clean`. This failure isn't related to my changes.

**Comment by cholin** [comment]
The failure was due an uncommited old `feeds.conf`. I checked out the original one. No routing errors anymore but it fails anyway with the same error message. If you look at the linked posted you see I built with `make clean && make -j5 V=s`. See http://paste.debian.net/hidden/dc1dea2a/.

**Comment by cholin** [comment]
Master builds fine and the only difference is your https://github.com/freifunk-berlin/firmware/commit/28be96633f0c55436c4484930ef2406723571f0d commit. When I add this line to the Makefile your branch builds as well.

**Comment by lynxis** [comment]
Ok. Fine. But this branch should fail because of missing dependencies in firmware creation (openvpn)

**Comment by lynxis** [comment]
It works as expected. 28da92bab4 (branch fix-unreported-imagebuilder-fail_test) fails on the buildbot.
There is another bug in the imagebuilder: The IB doesn't fail when some dependencies can not be resolved.
But it will fail on missing packages, when they are selected by the package.txt
