### ISSUE TITLE
[Statistiken: Schnittstellen] Gerätebezeichnungen fehlen

### ISSUE THREAD

**Issue by yjebos** [freifunk-berlin/firmware#235]
In den Statistiken zu den Schnittstellen fehlen die Bezeichnungen.
So ist leider nicht zu erkennen, für welches Gerät die Kurve erstellt wurde.
Bsp: "Transfer on"

**Comment by sarumpaet** [comment]
Bei meinen Geräten sehe ich das Problem nicht.
Welche Statistiken? (LuCI? Monitor? URL?)
Welche Hardware?
Welche Firmware?
Bitte Angaben nachreichen und Issue neu öffnen.
