### ISSUE TITLE
sysupgrade auf kathleen 0.1.x verliert OpenVPN bbbvpn-Zertifikate

### ISSUE THREAD

**Issue by wyae** [freifunk-berlin/firmware#238]
Das Update auf einem TP-Link TP-1043ND v1 per sysupgrade-File von http://buildbot.berlin.freifunk.net/buildbot/stable/0.1.0/ar71xx/default/ über Weboberfläche tut zwar, aber mit kleineren Tücken:

bbbvpn verliert seine Zertifikate (alle: ca, key, crt)

Nach deren Einspielen und manuellem OpenVPN-starten (über Weboberfläche) und tut's dann wieder - aber sind erst mal weg, und damit auch die OLSR-Anbindung.

**Comment by booo** [comment]
Wo lagen die Zertifikate und der Schlüssel?

**Comment by wyae** [comment]
Da das Einklickern über die Weboberfläche nicht funktionierte und auch die Anleitung nach http://bbb-vpn.berlin.freifunk.net/cgi-bin-index.html zu keinem Erfolg führte, habe ich das schließlich nach
http://cholin.spline.de/freifunk/bbb_vpn.html aufbauen können.

Die Zertiufikate lagen entsprechend in /etc/openvpn/

**Comment by cholin** [comment]
bbbvpn ist Handarbeit und wird von der Firmware bzw dem Wizard nicht out-of-the-box unterstützt. Zur Zeit werden folgende Zertifkate bei einem Sysupgrade gesichert:

```
/etc/openvpn/freifunk_client.crt
/etc/openvpn/freifunk_client.key
```

Siehe dazu [luci-app-ffwizard-berlin/lib-upgrade/openvpn](https://github.com/freifunk-berlin/firmware-packages/blob/73306cab7b477078554fc96a4399973ca815add8/utils/luci-app-ffwizard-berlin/lib-upgrade/openvpn) und [luci-app-ffwizard-berlin/Makefile#L53](https://github.com/freifunk-berlin/firmware-packages/blob/73306cab7b477078554fc96a4399973ca815add8/utils/luci-app-ffwizard-berlin/Makefile#L53). Wir könnten natürlich auch mittels glob/wildcards `*.crt` und `*.key` einfach alle Zertifkate und Schlüssel sichern.

**Comment by andrenarchy** [comment]
+1 für wildcards! Vllt auch noch `*.conf`?

**Comment by wyae** [comment]
seconded.
Dazu dann auch noch die *.ca damit die Zertifikatsketten erhalten bleiben.

Danke!

Volker

**Comment by booo** [comment]
Spricht etwas dagegen den ganzen Ordner `/etc/openvpn` zu behalten?

**Comment by andrenarchy** [comment]
@booo: nein. +1 für kompletten `/etc/openvpn`.

**Comment by cholin** [comment]
In `/etc/openvpn` liegt auch das `ffvpn-up.sh`-Skript. Das sollte nicht beibehalten werden bei einem sysupgrade. Würde mich als gegen den ganzen Ordner aussprechen.

@andrenarchy  wieso brauchst du `*.conf`, wenn diese doch aus der UCI-Konfiguration generiert werden? 
@wyae  von welchem ca sprichst du? CA und Cert von BBB-VPN und VPN03 haben jeweils eine `.crt`-Dateiendung (*freifunk-ca.crt*, *freifunk_client.key*,*bbb-vpn-ca.crt*,*bbb-vpn_X.crt*) und würden mit den Wildcards schon gesichert werden.

**Comment by andrenarchy** [comment]
@cholin: es gibt in UCI auch die Möglichkeit eine config à la
```
option config /etc/openvpn/my-vpn.conf
```
anzugeben.

**Comment by cholin** [comment]
Dann migrier deine Konfiguration nach UCI. Wir sollten nicht den Anspruch haben jegliche Konfigurationsparameter zu unterstützen.

**Comment by wyae** [comment]
Ah! Sorry, käsiges Gedächtnis: die CA-Zertifikate heißen ja üblicherweise *-ca.crt und nicht *.ca - sind also schon in der *.crt-Wildcard mit 'drin.

**Comment by lynxis** [comment]
Wieso ist denn /etc/openvpn/ nicht automatisch im sysupgrade includiert? Fehlt ein bb backport?Im trunk ist das schon so:
https://github.com/openwrt-mirror/openwrt/blob/master/package/network/services/openvpn/files/openvpn.upgrade

**Comment by booo** [comment]
@lynxis wird von uns überschrieben: https://github.com/freifunk-berlin/firmware-packages/blob/73306cab7b477078554fc96a4399973ca815add8/utils/luci-app-ffwizard-berlin/lib-upgrade/openvpn

**Comment by lynxis** [comment]
@boo dann weg weg mit unserem ueberschreiben. Der default ist gut!

**Comment by booo** [comment]
Ich denke auch, dass die Upgrade-Konfiguration von openwrt für openvpn gut ist, aber wir wollen wirklich nicht das `ffvpn-up.sh` backupen. Macht es Sinn, wenn wir das nach /lib/functions/ verschieben? Gibt es einen besseren Ort?

**Comment by lynxis** [comment]
/usr/lib/freifunk/ oder /lib/freifunk/ würde ich benutzen.

**Comment by wyae** [comment]
Das Problem besteht auch beim Update auf Kathleen 0.1.2

**Comment by booo** [comment]
@wyae Danke fürs Testen. Im nächsten Release sollte das Problem gelöst sein.
