### ISSUE TITLE
release codenames 

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#24]
We need fancy names for our releases. 

I suggest we name our releases after important female computer scientists, hackers, etc.

**Comment by andrenarchy** [comment]
Just stumbled upon [Margaret Hamilton](http://en.wikipedia.org/wiki/Margaret_Hamilton_%28scientist%29)...

**Comment by booo** [comment]
[Sophie Wilson](http://www.linuxvoice.com/sophie-wilson-acorn-and-the-development-of-arm/)

**Comment by booo** [comment]
https://fahrplan.events.ccc.de/congress/2016/Fahrplan/events/8233.html

**Comment by booo** [comment]
Another very interesting source: http://ethw.org/Oral-History:Women_in_Computing

**Comment by booo** [comment]
Just came across the inventor of the spanning tree protocol: https://en.wikipedia.org/wiki/Radia_Perlman
