### ISSUE TITLE
Missing libiwinfo-lua for status-page

### ISSUE THREAD

**Issue by basros** [freifunk-berlin/firmware#244]
Version: ```0.1.0 - 0.1.1-alpha```
Testet-Flavor: backbone 

Status-Page is not capable of displaying wifi information due to missing libiwinfo-lua. 
There's even a proper error message:
> Das Paket libiwinfo wird benötigt!
> Das libiwinfo-Paket ist nicht installiert. Dieses Paket muss für eine funktionierende WLAN-Konfiguration vorhanden sein!

This message is missleading, because ```libiwinfo``` is actually already installed but LuCI is missing ```libiwinfo-lua```

**Comment by booo** [comment]
I think the fastest solution would be to add it to the package list for the backbone firmware. A proper solution would fix the dependencies in the luci packages. But I'm not sure where to put this dependency.

Any opinions on this?
