### ISSUE TITLE
Build 0.2.0-alpha for mpc85xx

### ISSUE THREAD

**Issue by basros** [freifunk-berlin/firmware#255]
*Chaos Calmer 15.05-rc1* has been released!!

Thanks for taking the initiative to build 0.2.0-alpha (based on CC) for ar71xx!

Please build 0.2.0-alpha also for mpc85xx, preferable as profile `backbone`.

**Comment by sarumpaet** [comment]
That should already be the case :)
http://buildbot.berlin.freifunk.net/builders/mpc85xx/builds/540
http://buildbot.berlin.freifunk.net/buildbot/unstable/mpc85xx/540/
