### ISSUE TITLE
Traffic limiter limits the private AP as well as ffvpn

### ISSUE THREAD

**Issue by sarumpaet** [freifunk-berlin/firmware#257]
...since it's limiting the wan interface. It should probably limit the ffvpn interface (and get triggered on ffvpn up).

**Comment by booo** [comment]
The limiter should only limit the ffvpn interface. I guess we can change the interface here to ffvpn: https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/luci-app-ffwizard-berlin/luasrc/tools/freifunk/assistent/ffwizard.lua#L44

**Comment by booo** [comment]
Why should we trigger the qos on ifup events?

**Comment by sarumpaet** [comment]
The WAN interface might be down on boot or disappear temporarily (connected modem crashed, etc.). I just saw that qos-scripts uses an ifup script so fortunately this already gets handled. I'll update the defaults and write migration.
