### ISSUE TITLE
speedtest without flashplayer

### ISSUE THREAD

**Issue by Polynomdivison** [freifunk-berlin/firmware#259]
Hi,
I would prefer a speedtest (not speedtest.net) without flashplayer.
The flashplayer is very unsafe and often people who are using linux haven't installed flashplayer.
So please link another speedtest in the wizard.

**Comment by sarumpaet** [comment]
speedof.me perhaps? Any other suggestions?

**Comment by booo** [comment]
"It is the smartest and most accurate online bandwidth test." We should definitely use it!

**Comment by andrenarchy** [comment]
+1 for speedof.me

EOL of flash is near! \o/
