### ISSUE TITLE
olsr topology view

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#260]
For e.g. teaching purposes it would be nice to have a topology view for olsr in the router status interface. It's not necessary that the view is part of the default image. As far as I know there is a package for this somewhere in the openwrt ecosystem.

**Comment by sarumpaet** [comment]
What kind of topology view? Obviously you are not referring to the build-in map view or the table topology view?

**Comment by booo** [comment]
I talking about this: https://github.com/openwrt/luci/tree/master/applications/luci-app-olsr-viz

**Comment by booo** [comment]
Done with the next package update so I'm closing this.
