### ISSUE TITLE
Update der Community Profile (openwrt/luci)

### ISSUE THREAD

**Issue by FreifunkUFO** [freifunk-berlin/firmware#275]
Bitte aktualisiert mal die Community Profile in openwrt/luci (derzeit sind die nur als Patch vorhanden)
Sind diese noch meshwizard/meshkit - kompatibel?

Lt. https://github.com/freifunk-berlin/firmware/blob/master/patches/013-delete_non_existing_profiles.patch können die Profile "Pberg und Berlin NordOst" gelöscht werden!?

**Comment by FreifunkUFO** [comment]
siehe auch https://github.com/freifunk-berlin/firmware/issues/245

**Comment by booo** [comment]
Eins der Profile ist jetzt verschwunden. Das Pberg-Profile kann eigentlich auch weg, oder @stargieg ?

Kompatibilität zum meshwizard/meshkit testen wir zur Zeit nicht und werden wir in Zukunft auch eher nicht testen. Wir empfehlen auch niemandem einen anderen Wizard als den Berliner zu nutzen.

**Comment by sarumpaet** [comment]
Duplikat von #245
