### ISSUE TITLE
Firmware für den 841v10

### ISSUE THREAD

**Issue by mmalte** [freifunk-berlin/firmware#291]
Hallo Berlin!

Hier ist jemand aufgeschlagen der auf der Firmware für den 841v10 ist, könnt ihr ihm weiterhelfen?

https://forum.freifunk.net/t/tp-link-tl-wr841n-version-10-0-berliner-freifunk/8644

LG aus Aachen
MrMM

**Comment by sarumpaet** [comment]
Support für den 841v10 gibt es erst seit dem 26.10.2015 im OpenWrt Master:
http://git.openwrt.org/?p=openwrt.git;a=commitdiff;h=75c0f8d51ffe17a64ccd31a0b38f3fa8c119d8dd
http://git.openwrt.org/?p=openwrt.git;a=commitdiff;h=1cd7e6c1fd07527d2a6a7660c85e7e90160956a9
Falls das nicht davon in den nächsten Tagen einen Commit auch in CC gibt, können wir evtl. den Patch von Gluon übernehmen:
https://github.com/freifunk-gluon/gluon/blob/master/patches/openwrt/0031-ar71xx-fix-ath79_soc_rev-value-for-QCA9531-ver.-2.patch

**Comment by Benjarobbi** [comment]
Hi, hat sich jetzt etwas mehr getan? Gibt es mehr Infos?

**Comment by cpietsch** [comment]
würde mich auch interessieren

**Comment by SvenRoederer** [comment]
mit 2 commits am 5.12.2015 ist der V10-support nach CC geportet worden.
ich hab das mal bauen lassen :
+ alle anderen Änderungen for CC
+ update der community-profile für Berlin + Cottbus
+ support für TL-WR1043v3, DLink DIR505

http://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx/745/

**Comment by SvenRoederer** [comment]
da der o.g. ordner vom buildserver gelöscht wurde, hier ein aktueller: http://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx/797

**Comment by sarumpaet** [comment]
https://github.com/freifunk-berlin/firmware/commit/f45576c1dc21b3d46ac7179eab3d1fe2e8f52e39

**Comment by theincogtion** [comment]
Gibt es wirklich noch keine Lösung? Ich wäre auch an v10 interessiert. Wenn man einen neuen Kauft hat man in der Regel v10

**Comment by SvenRoederer** [comment]
@theincogtion  das Ticket ist geschlossen, weil unter o.g. commit der support für V10 für Kathleen 0.2.0 in der Firmware ist
http://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx/1035/

**Comment by theincogtion** [comment]
ok aber leider noch unstable?
