### ISSUE TITLE
PPP is disabled

### ISSUE THREAD

**Issue by stargieg** [freifunk-berlin/firmware#298]
Hi
Why is PPP disabled.
It make no sens to enable
kmod-usb-serial-wwan
and disable
 # CONFIG_PACKAGE_kmod-ppp is not set

I cant create a pppoe (DSL) conection or a ppp (UMTS) connection. :-(

**Comment by booo** [comment]
I guess you are the first person which really wants to use this. We can add the module. No problem. Can you prepare a pull request?

**Comment by stargieg** [comment]
Switch it on if you need it. What firmware do you use to access the Internet?

**Comment by andrenarchy** [comment]
@stargieg have you prepared a PR? I'd also vote for building the module. :smile:
