### ISSUE TITLE
check CONFIG_CLEAN_IPKG build option

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#299]
@sarumpaet My gut tells me that we implemented something like this somewhere.

"This removes all ipkg/opkg status data files from the target directory before building the root filesystem."

Maybe we should use this option.

**Comment by sarumpaet** [comment]
We get great issues like #262 then and break opkg completely, just to save a few kB. This is a last resort thing at best.

**Comment by booo** [comment]
Thanks for the clarification!
