### ISSUE TITLE
Fehlermeldung beim Restart nach Einrichtung der Freifunk-Installation

### ISSUE THREAD

**Issue by semirch** [freifunk-berlin/firmware#303]
Hallo, leider hab ich die Fehlermeldung nicht gespeichert... es kam irgendwas mit Stopped und Exception nach dem Flashen und Daten eingeben (er startet dann ja neu).
Leider hab ich scheinbar auch das richtige Root-Passwort nicht mitgeschnitten.
Was mache ich jetzt?
Dank und Grüße, Semir

**Comment by sarumpaet** [comment]
http://wiki.openwrt.org/de/doc/howto/generic.failsafe
...oder einfach mal an einem Mittwoch in die c-base kommen.
