### ISSUE TITLE
remove redundant geo-location from uci-config "system.system"

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#307]
in uci "System.System" (/etc/config/system) are 2 sets of parameters for geo-location.
Is this really required to have them?

see http://lists.berlin.freifunk.net/pipermail/berlin/2015-November/029964.html

**Comment by SvenRoederer** [comment]
I already checked the code and removed the "lonlat" entry.
Trying to complie and test  ....

**Comment by booo** [comment]
Please take a look at the olsrd init script and the owm.lua script.

**Comment by SvenRoederer** [comment]
send pull-request for this
