### ISSUE TITLE
add community-profile cottbus

### ISSUE THREAD

**Issue by ffcb** [freifunk-berlin/firmware#309]
Im Master von OpenWrt wurde der Commit https://github.com/openwrt/luci/commit/3bae3c7f5e8c383e481667fcfeae7765a1dacc75 mit unserem Community-Profil gemerged. Könnt ihr dieses Profil bitte auch in kathleen integrieren? Danke

**Comment by booo** [comment]
I will try to take look at this.

**Comment by FreifunkUFO** [comment]
gibt es schon erste Erfahrungen mit nicht-Berliner Profilen?

**Comment by SvenRoederer** [comment]
in build https://github.com/SvenRoederer/openwrt-luci/tree/for-15.05_freifunk-berlin_unstable-SAm0815 ist es schin drin. 
ich will das alles stückweise richtung kathleem 0.2.0 pushen

**Comment by ffcb** [comment]
ich habe auf einem nexx wt3020f mit der aktuellen weekly-alpha von kathleen 0.2.0 das profil nach dem flashen und einem reset per ssh manuell eingespielt. nach dem durchlauf mit dem freifunkassistenten hat sich der nexx sofort mit dem vorhandenen mesh verbunden

**Comment by SvenRoederer** [comment]
these profiles are per default always included in all builds of branch "unstable_SAm0815" since 12. Jan 2016 (https://github.com/SvenRoederer/openwrt-luci/commit/8ecf17070f839a37a65e6b415a9efee77a4599f4). Check version.txt in root-folder of your firmware-build

**Comment by SvenRoederer** [comment]
closed by https://github.com/freifunk-berlin/firmware/commit/3be098e246a3d82121c05bbdc213d2dd06b70f11
