### ISSUE TITLE
no uplink-route for DHCP-clients

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#316]
in build 718 (http://buildbot.berlin.freifunk.net/builders/ar71xx/builds/718) (https://github.com/freifunk-berlin/firmware-packages/tree/luci-mod-freifunk-ui) there is no uplink-route for clients on interface "br-dhcp".

"ip rule" is not showing any "prio 19999" rules, so also no rule to "olsr-tunnel".
> ip rule add iif br-dhcp pref 19999 lookup olsr-tunnel

makes routing work

on my non-meshing router, only VPN03 for uplink I got this directly after bootup
<pre>
root@sam0815-test:/# ip rule
0:      from all lookup 128 
1:      from all lookup local 
1000:   from all lookup olsr 
2000:   from all lookup localnets 
20000:  from all iif wlan0-adhoc-2 lookup olsr-default 
20000:  from all iif ffvpn lookup olsr-tunnel 
20001:  from all iif ffvpn unreachable
32766:  from all lookup main 
32767:  from all lookup default 
100000: from all lookup olsr-tunnel 
100010: from all lookup olsr-default 
root@sam0815-test:/# ip route show table olsr
10.31.21.125 dev wlan0-adhoc-2  scope link 
10.230.197.208/28 dev br-dhcp  scope link 
172.31.240.0/20 dev ffvpn  scope link 
192.168.8.0/24 dev eth0  scope link 
root@sam0815-test:/# ip route show table localnets
10.31.21.125 dev wlan0-adhoc-2  scope link 
10.230.197.208/28 dev br-dhcp  scope link 
172.31.240.0/20 dev ffvpn  scope link 
192.168.8.0/24 dev eth0  scope link 
root@sam0815-test:/# ip route show table olsr-default
root@sam0815-test:/# ip route show table olsr-tunnel
default via 172.31.240.1 dev ffvpn 
172.31.240.0/20 dev ffvpn  scope link  src 172.31.241.31 
root@sam0815-test:/# ip route get 8.8.8.8 from 10.230.197.221 iif br-dhcp
8.8.8.8 from 10.230.197.221 via 192.168.8.1 dev eth0 
    cache  iif br-dhcp
root@sam0815-test:/# ip rule add iif br-dhcp lookup olsr-tunnel pref 19999
root@sam0815-test:/# ip route get 8.8.8.8 from 10.230.197.221 iif br-dhcp
8.8.8.8 from 10.230.197.221 via 172.31.240.1 dev ffvpn 
    cache  iif br-dhcp
root@sam0815-test:/# 
</pre>

**Comment by sarumpaet** [comment]
That branch is by me, not stargieg. :) Thanks for testing! I'm actually surprised that it works at all, as that specific build was more of a test whether the firmware works without both firewall and iptables packages (note the last commit "WIP" :) ). It'd be perfect if you could have a look or help with further testing. :)

**Comment by SvenRoederer** [comment]
loooks like I got lost in the names here ...
I also like to see some progress, esp as these chnges help to reduce the size for these damn tiny 4MB-flash routers.
Think, if nobody has concerns to go into this direction for 0.2.0 , I'm happy to help

**Comment by sarumpaet** [comment]
https://github.com/freifunk-berlin/firmware-packages/pull/62 (plus PR 66) and the luci-mod-freifunk-ui package are ready for merge I'd say. Fixing this issue can come later, as can any detail work or further improvements (e.g., launching OpenVPN via procd). We should merge PRs more quickly instead of letting them lie around forever, especially if they fix crucial bugs. I'd be interested in how many connections to VPN03 come from inside the mesh at the moment. ;)

**Comment by booo** [comment]
It's a shame that the pull request is laying around so long but I don't want to merge it as it is. I will try to comment on this in the pull request.

**Comment by SvenRoederer** [comment]
seems that this missing uplink / faulty routing only existes when doing a fresh install. on a upgraded system from 0.1.2 the uplink was ok ("19999 rules were installed")

**Comment by SvenRoederer** [comment]
I made a diff over the generated backup-file between a upgraded and fresh installed router. some lines are no real differences, as I used different IP-ranges in the wizard.
Maybe you can spot the relevant difference
<pre>
sven@hypnosis:/tmp/config$ diff -uNr etc_upgrade/ etc_fresh/    
diff -uNr etc_upgrade/config/defaults etc_fresh/config/defaults
--- etc_upgrade/config/defaults 2015-07-02 11:21:27.000000000 +0200
+++ etc_fresh/config/defaults   2016-01-03 16:10:30.000000000 +0100
@@ -1,7 +1,6 @@
 
 config packages 'default'
        option dhcp '1'
-       option firewall '1'
        option network '1'
        option olsrd '1'
        option openvpn '1'
diff -uNr etc_upgrade/config/dhcp etc_fresh/config/dhcp
--- etc_upgrade/config/dhcp     2016-01-02 02:55:51.000000000 +0100
+++ etc_fresh/config/dhcp       2016-01-03 16:20:24.000000000 +0100
@@ -14,14 +14,7 @@
        option readethers '1'
        option leasefile '/tmp/dhcp.leases'
        option resolvfile '/tmp/resolv.conf.auto'
-
-config dhcp 'lan'
-       option interface 'lan'
-       option start '100'
-       option limit '150'
-       option leasetime '12h'
-       option dhcpv6 'server'
-       option ra 'server'
+       option localservice '1'
 
 config dhcp 'wan'
        option interface 'wan'
@@ -29,11 +22,11 @@
 
 config domain 'frei_funk'
        option name 'frei.funk'
-       option ip '10.230.192.1'
+       option ip '10.230.197.209'
 
 config domain 'frei_funk_ipv6'
        option name 'frei.funk'
-       option ip 'fde7:d3d3:80b1::1'
+       option ip 'fdc9:cda0:0e43::1'
 
 config odhcpd 'odhcpd'
        option maindhcp '0'
@@ -49,5 +42,5 @@
        option dhcpv6 'server'
        option ra 'server'
        option start '2'
-       option limit '253'
+       option limit '13'
 
diff -uNr etc_upgrade/config/ffwizard etc_fresh/config/ffwizard
--- etc_upgrade/config/ffwizard 2015-07-02 11:29:59.000000000 +0200
+++ etc_fresh/config/ffwizard   2016-01-03 16:20:24.000000000 +0100
@@ -6,7 +6,7 @@
        option enableStats '0'
        option private_ap '0'
        option ssid 'test.berlin.freifunk.net'
-       option dhcpmesh '10.230.192.0/24'
+       option dhcpmesh '10.230.197.208/28'
        option meship_radio0 '10.31.21.125'
        option runbefore 'true'
 
diff -uNr etc_upgrade/config/firewall etc_fresh/config/firewall
--- etc_upgrade/config/firewall 2016-01-02 02:55:51.000000000 +0100
+++ etc_fresh/config/firewall   1970-01-01 01:00:00.000000000 +0100
@@ -1,119 +0,0 @@
-
-config defaults
-       option syn_flood '1'
-       option input 'ACCEPT'
-       option output 'ACCEPT'
-       option forward 'REJECT'
-       option drop_invalid '0'
-
-config zone
-       option name 'wan'
-       option masq '1'
-       option network 'wan'
-       option forward 'REJECT'
-       option output 'ACCEPT'
-       option local_restrict '1'
-       option input 'ACCEPT'
-
-config rule
-       option name 'Allow-DHCP-Renew'
-       option src 'wan'
-       option proto 'udp'
-       option dest_port '68'
-       option target 'ACCEPT'
-       option family 'ipv4'
-
-config rule
-       option name 'Allow-Ping'
-       option src 'wan'
-       option proto 'icmp'
-       option icmp_type 'echo-request'
-       option family 'ipv4'
-       option target 'ACCEPT'
-
-config rule
-       option name 'Allow-DHCPv6'
-       option src 'wan'
-       option proto 'udp'
-       option src_ip 'fe80::/10'
-       option src_port '547'
-       option dest_ip 'fe80::/10'
-       option dest_port '546'
-       option family 'ipv6'
-       option target 'ACCEPT'
-
-config rule
-       option name 'Allow-ICMPv6-Input'
-       option src 'wan'
-       option proto 'icmp'
-       option icmp_type 'echo-request echo-reply destination-unreachable packet-too-big time-exceeded bad-header unknown-header-type router-solicitation neighbour-solicitation router-advertisement neighbour-advertisement'
-       option limit '1000/sec'
-       option family 'ipv6'
-       option target 'ACCEPT'
-
-config rule
-       option name 'Allow-ICMPv6-Forward'
-       option src 'wan'
-       option dest '*'
-       option proto 'icmp'
-       option icmp_type 'echo-request echo-reply destination-unreachable packet-too-big time-exceeded bad-header unknown-header-type'
-       option limit '1000/sec'
-       option family 'ipv6'
-       option target 'ACCEPT'
-
-config include
-       option path '/etc/firewall.user'
-
-config zone 'zone_freifunk'
-       option input 'ACCEPT'
-       option forward 'REJECT'
-       option name 'freifunk'
-       option output 'ACCEPT'
-       option network 'tunl0 wireless0 dhcp ffvpn'
-       option device 'tnl_+'
-
-config forwarding
-       option dest 'freifunk'
-       option src 'freifunk'
-
-config rule
-       option proto 'icmp'
-       option target 'ACCEPT'
-       option src 'freifunk'
-
-config rule
-       option dest_port '80'
-       option proto 'tcp'
-       option target 'ACCEPT'
-       option src 'freifunk'
-
-config rule
-       option dest_port '443'
-       option proto 'tcp'
-       option target 'ACCEPT'
-       option src 'freifunk'
-
-config rule
-       option dest_port '22'
-       option proto 'tcp'
-       option target 'ACCEPT'
-       option src 'freifunk'
-
-config advanced
-       option tcp_westwood '1'
-       option tcp_ecn '0'
-       option ip_conntrack_max '8192'
-
-config forwarding
-       option dest 'freifunk'
-       option src 'wan'
-
-config rule
-       option proto 'udp'
-       option name 'Reject-VPN-over-ff-2'
-       option dest 'freifunk'
-       option dest_ip '77.87.49.66'
-       option dest_port '1194'
-       option target 'REJECT'
-       option family 'ipv4'
-
diff -uNr etc_upgrade/config/luci etc_fresh/config/luci
--- etc_upgrade/config/luci     2016-01-02 02:55:53.000000000 +0100
+++ etc_fresh/config/luci       2016-01-03 16:10:30.000000000 +0100
@@ -1,8 +1,8 @@
 
 config core 'main'
        option lang 'auto'
-       option resourcebase '/luci-static/resources'
        option mediaurlbase '/luci-static/bootstrap'
+       option resourcebase '/luci-static/resources'
 
 config extern 'flash_keep'
        option uci '/etc/config/'
diff -uNr etc_upgrade/config/network etc_fresh/config/network
--- etc_upgrade/config/network  2015-07-02 11:30:06.000000000 +0200
+++ etc_fresh/config/network    2016-01-03 16:20:24.000000000 +0100
@@ -6,7 +6,7 @@
        option netmask '255.0.0.0'
 
 config globals 'globals'
-       option ula_prefix 'fde7:d3d3:80b1::/48'
+       option ula_prefix 'fdc9:cda0:0e43::/48'
 
 config interface 'wan'
        option ifname 'eth0'
@@ -14,7 +14,7 @@
        option peerdns '0'
 
 config interface 'wan6'
-       option ifname '@wan'
+       option ifname 'eth0'
        option proto 'dhcpv6'
        option peerdns '0'
 
@@ -44,20 +44,20 @@
        option lookup 'localnets'
        option priority '2000'
 
-config rule 'olsr_tunnel_tunl0_ipv4'
+config rule 'olsr_tunnel_freifunk_ipv4'
        option lookup 'olsr-tunnel'
        option priority '19999'
-       option in 'tunl0'
+       option in 'freifunk'
 
-config rule 'olsr_default_tunl0_ipv4'
+config rule 'olsr_default_freifunk_ipv4'
        option lookup 'olsr-default'
        option priority '20000'
-       option in 'tunl0'
+       option in 'freifunk'
 
-config rule 'olsr_default_unreachable_tunl0_ipv4'
+config rule 'olsr_default_unreachable_freifunk_ipv4'
        option action 'unreachable'
        option priority '20001'
-       option in 'tunl0'
+       option in 'freifunk'
 
 config interface 'wireless0'
        option netmask '255.255.255.255'
@@ -69,53 +69,8 @@
        option proto 'static'
        option dns '85.214.20.141 213.73.91.35 194.150.168.168 2001:4ce8::53 2001:910:800::12'
        option ifname 'eth1'
-       option netmask '255.255.255.0'
+       option netmask '255.255.255.240'
        option ip6assign '64'
-       option ipaddr '10.230.192.1'
+       option ipaddr '10.230.197.209'
        option type 'bridge'
 
-config rule 'olsr_tunnel_wireless0_ipv4'
-       option lookup 'olsr-tunnel'
-       option priority '19999'
-       option in 'wireless0'
-
-config rule 'olsr_default_wireless0_ipv4'
-       option lookup 'olsr-default'
-       option priority '20000'
-       option in 'wireless0'
-
-config rule 'olsr_default_unreachable_wireless0_ipv4'
-       option action 'unreachable'
-       option priority '20001'
-       option in 'wireless0'
-
-config rule 'olsr_tunnel_dhcp_ipv4'
-       option lookup 'olsr-tunnel'
-       option priority '19999'
-       option in 'dhcp'
-
-config rule 'olsr_default_dhcp_ipv4'
-       option lookup 'olsr-default'
-       option priority '20000'
-       option in 'dhcp'
-
-config rule 'olsr_default_unreachable_dhcp_ipv4'
-       option action 'unreachable'
-       option priority '20001'
-       option in 'dhcp'
-
-config rule 'olsr_tunnel_ffvpn_ipv4'
-       option lookup 'olsr-tunnel'
-       option priority '19999'
-       option in 'ffvpn'
-
-config rule 'olsr_default_ffvpn_ipv4'
-       option lookup 'olsr-default'
-       option priority '20000'
-       option in 'ffvpn'
-
-config rule 'olsr_default_unreachable_ffvpn_ipv4'
-       option action 'unreachable'
-       option priority '20001'
-       option in 'ffvpn'
-
diff -uNr etc_upgrade/config/olsrd etc_fresh/config/olsrd
--- etc_upgrade/config/olsrd    2015-07-02 11:29:59.000000000 +0200
+++ etc_fresh/config/olsrd      2016-01-03 16:20:24.000000000 +0100
@@ -65,6 +65,6 @@
        option interface 'wireless0'
 
 config Hna4
-       option netmask '255.255.255.0'
-       option netaddr '10.230.192.0'
+       option netmask '255.255.255.240'
+       option netaddr '10.230.197.208'
 
diff -uNr etc_upgrade/config/olsrd6 etc_fresh/config/olsrd6
--- etc_upgrade/config/olsrd6   2015-07-02 11:29:59.000000000 +0200
+++ etc_fresh/config/olsrd6     2016-01-03 16:20:24.000000000 +0100
@@ -50,5 +50,5 @@
 
 config Hna6
        option prefix '48'
-       option netaddr 'FDE7:D3D3:80B1:0:0:0:0:0'
+       option netaddr 'fdc9:cda0:e43::'
 
diff -uNr etc_upgrade/config/openvpn etc_fresh/config/openvpn
--- etc_upgrade/config/openvpn  2016-01-02 02:55:51.000000000 +0100
+++ etc_fresh/config/openvpn    2016-01-03 16:20:29.000000000 +0100
@@ -1,24 +1,9 @@
 
 config openvpn 'ffvpn'
+       option enabled '0'
        option client '1'
-       option nobind '1'
-       option proto 'udp'
-       option dev 'ffvpn'
-       option dev_type 'tun'
-       option persist_key '1'
-       option keepalive '10 60'
-       option ns_cert_type 'server'
-       option comp_lzo 'no'
-       option script_security '2'
-       option cipher 'none'
-       option mssfix '1300'
        list remote 'vpn03.berlin.freifunk.net 1194 udp'
        list remote 'vpn03-backup.berlin.freifunk.net 1194 udp'
-       option ca '/etc/openvpn/freifunk-ca.crt'
-       option cert '/etc/openvpn/freifunk_client.crt'
-       option key '/etc/openvpn/freifunk_client.key'
-       option status '/var/log/openvpn-status-ffvpn.log'
-       option route_nopull '1'
+       option mssfix '1300'
        option up '/lib/freifunk/ffvpn-up.sh'
-       option enabled '0'
 
diff -uNr etc_upgrade/config/qos etc_fresh/config/qos
--- etc_upgrade/config/qos      2016-01-02 02:55:52.000000000 +0100
+++ etc_fresh/config/qos        1970-01-01 01:00:00.000000000 +0100
@@ -1,67 +0,0 @@
-
-config classify
-       option target 'Priority'
-       option ports '22,53'
-       option comment 'ssh, dns'
-
-config classify
-       option target 'Normal'
-       option proto 'tcp'
-       option ports '20,21,25,80,110,443,993,995'
-       option comment 'ftp, smtp, http(s), imap'
-
-config classify
-       option target 'Express'
-       option ports '5190'
-       option comment 'AOL, iChat, ICQ'
-
-config default
-       option target 'Express'
-       option proto 'udp'
-       option pktsize '-500'
-
-config reclassify
-       option target 'Priority'
-       option proto 'icmp'
-
-config default
-       option target 'Bulk'
-       option portrange '1024-65535'
-
-config classgroup 'Default'
-       option classes 'Priority Express Normal Bulk'
-       option default 'Normal'
-
-config class 'Priority'
-       option packetsize '400'
-       option avgrate '10'
-       option priority '20'
-
-config class 'Priority_down'
-       option packetsize '1000'
-       option avgrate '10'
-
-config class 'Express'
-       option packetsize '1000'
-       option avgrate '50'
-       option priority '10'
-
-config class 'Normal'
-       option packetsize '1500'
-       option packetdelay '100'
-       option avgrate '10'
-       option priority '5'
-
-config class 'Normal_down'
-       option avgrate '20'
-
-config class 'Bulk'
-       option avgrate '1'
-       option packetdelay '200'
-
-config interface 'ffvpn'
-       option enabled ''\''1'\'''
-       option download ''\''6000'\'''
-       option upload ''\''1000'\'''
-       option classgroup ''\''Default'\'''
-
diff -uNr etc_upgrade/config/system etc_fresh/config/system
--- etc_upgrade/config/system   2016-01-02 02:55:52.000000000 +0100
+++ etc_fresh/config/system     2016-01-03 16:19:44.000000000 +0100
@@ -1,11 +1,11 @@
 
 config system
+       option version '0.2.0-alpha.3028108'
        option cronloglevel '10'
        option zonename 'Europe/Berlin'
        option timezone 'CET-1CEST,M3.5.0,M10.5.0/3'
        option hostname 'sam0815-test'
        option location 'Berlin'
-       option version '0.2.0-alpha.bac898c'
 
 config timeserver 'ntp'
        list server '0.openwrt.pool.ntp.org'
diff -uNr etc_upgrade/config/ucitrack etc_fresh/config/ucitrack
--- etc_upgrade/config/ucitrack 2016-01-02 02:55:53.000000000 +0100
+++ etc_fresh/config/ucitrack   2016-01-03 16:10:30.000000000 +0100
@@ -18,6 +18,10 @@
 
 config dhcp
        option init 'dnsmasq'
+       list affects 'odhcpd'
+
+config odhcpd
+       option init 'odhcpd'
 
 config dropbear
        option init 'dropbear'
@@ -55,9 +59,6 @@
 
 config freifunk-policyrouting
        list exec '/etc/init.d/freifunk-policyrouting restart'
-
-config freifunk-policyrouting
-       list exec '/etc/init.d/freifunk-policyrouting restart'
 
 config olsrd
        option init 'olsrd'
diff -uNr etc_upgrade/config/uhttpd etc_fresh/config/uhttpd
--- etc_upgrade/config/uhttpd   2015-07-02 11:21:25.000000000 +0200
+++ etc_fresh/config/uhttpd     2016-01-03 16:10:29.000000000 +0100
@@ -4,6 +4,7 @@
        list listen_http '[::]:80'
        list listen_https '0.0.0.0:443'
        list listen_https '[::]:443'
+       option redirect_https '1'
        option home '/www'
        option max_requests '3'
        option max_connections '100'
@@ -20,8 +21,8 @@
 config cert 'px5g'
        option days '730'
        option bits '1024'
-       option country 'DE'
-       option state 'Berlin'
-       option location 'Berlin'
+       option country 'ZZ'
+       option state 'Somewhere'
+       option location 'Uknown'
        option commonname 'OpenWrt'
 
diff -uNr etc_upgrade/config/wireless etc_fresh/config/wireless
--- etc_upgrade/config/wireless 2015-07-02 11:29:59.000000000 +0200
+++ etc_fresh/config/wireless   2016-01-03 16:20:24.000000000 +0100
@@ -6,7 +6,7 @@
        option disabled '0'
        option country 'DE'
        option doth '0'
-       option hwmode '11ngb'
+       option hwmode '11bgn'
        option diversity '1'
        option channel '13'
 
diff -uNr etc_upgrade/crontabs/root etc_fresh/crontabs/root
--- etc_upgrade/crontabs/root   2015-07-02 11:30:00.000000000 +0200
+++ etc_fresh/crontabs/root     2016-01-03 16:20:28.000000000 +0100
@@ -1,4 +1,4 @@
-12 * * * *     /usr/sbin/owm.lua
+26 * * * *     /usr/sbin/owm.lua
 */5 * * * *    killall -HUP dnsmasq
 */5 * * * *    /usr/sbin/ff_olsr_watchdog
 0 6 * * * ifup wan
Binärdateien etc_upgrade/dropbear/dropbear_dss_host_key und etc_fresh/dropbear/dropbear_dss_host_key sind verschieden.
Binärdateien etc_upgrade/dropbear/dropbear_rsa_host_key und etc_fresh/dropbear/dropbear_rsa_host_key sind verschieden.
diff -uNr etc_upgrade/shadow etc_fresh/shadow
--- etc_upgrade/shadow  2015-07-02 11:29:05.000000000 +0200
+++ etc_fresh/shadow    2016-01-03 16:19:26.000000000 +0100
@@ -1,4 +1,4 @@
-root:$1$HvqSMuKv$rxqQxt546CJcmoLwJobm4/:16618:0:99999:7:::
+root:$1$xWecZWws$x1oe8J0EfOoDmbqebV5171:16803:0:99999:7:::
 daemon:*:0:0:99999:7:::
 ftp:*:0:0:99999:7:::
 network:*:0:0:99999:7:::
</pre>

**Comment by sarumpaet** [comment]
Let's keep this in mind. Closing this as we typically don't create issues for bugs in dev-only builds.
