### ISSUE TITLE
TP-Link CPE210

### ISSUE THREAD

**Issue by Ainadilion** [freifunk-berlin/firmware#326]
Beim Versuch die entsprechende Datei im Menü einzuspielen, erfolft folgende Fehlermeldung: The hardware version is not supported. Wie kann der Router geflasht werden?
mfg Steffen

**Comment by SvenRoederer** [comment]
Welche Firmwareversion willst du flashen?
auf welche Hardwareversion willst du flashen?

Hardwareversion V1.1 ist bisher nur in kathleen-0.2.x unterstützt

**Comment by Ainadilion** [comment]
Hallo,

derzeit ist folgende Firmware auf dem Gerät: 1.3.0 Build 20150612 Rel. 50957
Ich versuche diese zu
installieren: openwrt-ar71xx-generic-cpe210-220-510-520-squashfs-factory

mfg
Steffen

Am 06.02.2016 00:40 schrieb "Sven Roederer" <notifications@github.com>:

**Comment by booo** [comment]
@Ainadilion Wo kommt die Firmware her, die du flashen willst?

Wahrscheinlich hast du Versin 1.1 des Routers und der wird nur im [unstable branch](http://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx/761/default/) unterstützt.

**Comment by Ainadilion** [comment]
Hallo, hatte mir die Firmware von der Berliner Freifunkseite
heruntergeladen, muss ich bei der Version im Link etwas Besonderes beachten?

mfg Steffen

Am 6. Februar 2016 um 11:47 schrieb Philipp Borgers <
notifications@github.com>:

**Comment by SvenRoederer** [comment]
welche Hardwareversion du hast, steht neben dem kleinen aufkleber mit der S/N

**Comment by Ainadilion** [comment]
Hi, die Version lautet Ver: 1.1.
mfg Steffen

2016-02-06 12:43 GMT+01:00 Sven Roederer <notifications@github.com>:

**Comment by sarumpaet** [comment]
Siehe https://wiki.freifunk.net/Berlin:Firmware#Router-spezifische_Hinweise , der v1.1 wird von den aktuellen Releases noch nicht unterstützt, booo hatte bereits einen Link zu Entwicklungs-Images geschickt.

**Comment by Ainadilion** [comment]
Hallo, also macht es Sinn noch etwas zu warten?

mfg Steffen

2016-02-07 12:21 GMT+01:00 sarumpaet <notifications@github.com>:

**Comment by sarumpaet** [comment]
Das verlinkte Image kannst Du gerne ausprobieren, das läuft bei anderen Leuten problemlos.

**Comment by Ainadilion** [comment]
Hallo,

hab jetzt das Image eingespielt, jedoch gibt es keine Verbindung über
*http://192.168.42.1/
<http://192.168.42.1/>. Gibt es hier auch Besonderheiten zu beachten für
die Konfiguration?*

*mfg Steffen*

2016-02-07 13:02 GMT+01:00 sarumpaet <notifications@github.com>:

**Comment by Ainadilion** [comment]
Hallo, Kommando zurück, jetzt geht es, musste nur auf automatisches
Beziehen der IP-Adresse zurückschalten ;-)

mfg Steffen

Am 7. Februar 2016 um 17:20 schrieb Ainadilion . <wischekurier@gmail.com>:

**Comment by SvenRoederer** [comment]
hast du schonmal die andere Netzwerkbuchse probiert?

sonst meld dich mal auf der Mailingliste, da lesen mehr leute, die praktische Erfahrungen haben.
