### ISSUE TITLE
freifunk-assistent:  enable wan-interface in crontab

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#344]
The assistent is setting up a cronjob to call "ifup" daily at 6am ... is this still required?

https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/luci-app-ffwizard-berlin/luasrc/controller/assistent/assistent.lua#L115

**Comment by booo** [comment]
I don't think so. I will run a little unrepresentative test on my local setup and prepare a patch to remove the entry if the test is successful.

**Comment by SvenRoederer** [comment]
I also have some setups which don't show any issues w/o this entry.

So agreed toremove it?

**Comment by booo** [comment]
Please remove the crontab entry.

**Comment by bobster-galore** [comment]
done?

**Comment by SvenRoederer** [comment]
merged in https://github.com/freifunk-berlin/firmware-packages/commit/1288c3dc901fb9e509748a4ea4c9e3d0a7b7601b
