### ISSUE TITLE
Paket-Priorisierung an Stelle von qos?

### ISSUE THREAD

**Issue by smilebef** [freifunk-berlin/firmware#362]
Wäre es nicht besser so wie die in der Weimarfirmware mit tc umgesetzte Paketpriorisierung (olsrd) auch an stelle von qos zu verwenden? Ich frage weil ich keine Ahnung habe.

**Comment by sarumpaet** [comment]
Die QoS-Skripte werfen auch nur ein paar tc-Kommandos aus, soll heißen, das Programm "tc" setzt "Quality of Service" um.
