### ISSUE TITLE
ff_olsr_watchdog ignoriert olsrd disable

### ISSUE THREAD

**Issue by SvenSFS** [freifunk-berlin/firmware#380]
Hallo,
mir ist aufgefallen das der ff_olsr_watchdog den Umstand
ignoriert das olsrd bei mir abgeschaltet ist.

Aufgrund der massiven last die olsrd verursacht hab
ich den olsrd abgeschaltet und über /etc/init.d/olsrd disable
gesetzt.

Jedoch wird das ignoriert, ich musste das über dir crontab 
auf die harte Tour abschalten, also mit # aus dokumentiert.

System ist ne NSM2 mit kathleen 0.1.2, based OpenWRT r44952

Sven

**Comment by SvenRoederer** [comment]
"ff_olsr_watchdog" gibt's im nächsten release (kathleen 0.2.0) nicht mehr

**Comment by jal2** [comment]
@SvenSFS 
Gibt es bei nach dem Abschalten mit "/etc/init.d/olsrd disable" und einem Neustart die Files /var/run/olsrd*.pid denn noch? Eigentlich arbeitet ff_olsr_watchdog nur dann, wenn es olsrd.pid oder olsrd4.pid dort vorfindet. Was bei Dir nicht der Fall sein sollte. Oder ich verstehe den Lua Code nicht.

**Comment by booo** [comment]
Alternativ an die Interfaces in der olsrd-Konfiguration "option ignore 1" schreiben und der OLSRD sollte nicht mehr dauerhaft gestartet werden.

**Comment by sarumpaet** [comment]
ff_olsr_watchdog ist noch da, nur der ffwatchd ist weggefallen. Aufgerufen wird ff_olsr_watchdog in /etc/init.d/freifunk. Siehe auch https://github.com/freifunk-berlin/firmware/issues/400 .

**Comment by booo** [comment]
Nach einem `/etc/init.d/olsrd disable` und dem Entfernen der Pid-Files, des olsrd.watchdog Files und der generierten Konfiguration im /var/* startet bei mir der OLSR nicht mehr.

Kann ff_olsr_watchdog kein Pid-File finden oder sollte /var/run/olsrd.watchdog nicht vorhanden sein, wird auch kein OLSR-Prozess gestartet.

Ich denke der ff_olsr_watchdog funktioniert so wie es von den Erfinderinnen intendiert war, deshalb schließe ich das Ticket hiermit. Ob das ein sinnvoller Watchdog ist, sollten wir ggf. in einem anderen Ticket diskutieren.
