### ISSUE TITLE
OWM: the board is not differing between NSM2 and NSM5

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#390]
all NanoStationsM are grouped together, no matter of 5GHz or 2GHz. --> see http://berlin.freifunk.net/network/stats/

Do we want to distinguish between these bands?

**Comment by SvenRoederer** [comment]
this can be easy done by just looking up the TX-channel and adding the to the string returned in https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/luci-app-owm/luasrc/owm.lua#L276

**Comment by sarumpaet** [comment]
I'll try adding this to the stats webpage directly; that seems to be a better/easier place for such a hack.

**Comment by SvenRoederer** [comment]
I'm pretty sure, there are some differences in the RF-filters behind the Wifi-chip.

but let's go as you did.
