### ISSUE TITLE
wizard-backend: apply system config

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#392]
The following options should be read from `config.json` and be set in the system config:
- [x] hostname
- [ ] password
- [ ] ssh-keys

@lynxis created an initial version here:

https://github.com/freifunk-berlin/firmware-packages/blob/wizard2/utils/freifunk-berlin-wizard-backend/files/etc/ffwizard.d/10-system.sh

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
