### ISSUE TITLE
wizard-backend: apply network config

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#393]
The following options should be read from `config.json` and applied to the network and wireless config:
- [ ] wifi options (channel, mode, ssid, mesh id, batman vlan)
- [ ] batman device
- [ ] v6 prefix
- [ ] v4 mesh ips (radioX and lan)
- [ ] v4 dhcp subnet (if `distribute` is activated)

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
