### ISSUE TITLE
wizard-backend: apply olsrd config

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#394]
olsrd for ipv4 should be configured for all mesh interfaces.

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.

**Comment by SvenRoederer** [comment]
Somehow relates to #294.
