### ISSUE TITLE
wizard-backend: apply olsrd2 config

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#395]
olsrd2 for ipv6 should be configured for all mesh interfaces.

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.

**Comment by SvenRoederer** [comment]
relates to #394 and also somehow to #294
