### ISSUE TITLE
wizard-backend: receive and process config.json via uhttpd/rpc.d

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#397]
initial code available here:
https://github.com/freifunk-berlin/firmware-packages/blob/wizard2/utils/freifunk-berlin-wizard-backend/files/rpcd/ffwizard

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
