### ISSUE TITLE
Use LEDE instead of OpenWRT

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/firmware#407]
Using the [LEDE](https://www.lede-project.org/start) project should be easy. It is where the development goes to. Let us discuss it here.

**Comment by lynxis** [comment]
look at the lede branch...

**Comment by SvenRoederer** [comment]
as we are planning this for the next major-release I'll close this here

**Comment by SvenRoederer** [comment]
@niccokunzmann I put the commits we already have to support LEDE-build into a branch in my Repo (https://github.com/SvenRoederer/freifunk-berlin-firmware/tree/build_with_lede) from this I added some "compatibility hacks" to build with current buildbot-setting (see https://github.com/freifunk-berlin/firmware/tree/SAm0815/build_with_lede-hack_for_buildbot).
This all is based on LEDE and stuff of end December 2016.

**Comment by SvenRoederer** [comment]
See also #412
