### ISSUE TITLE
no WAN-interface on NSxLoco (maybe other singleport routers)

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#410]
Es gab ein paar User, die die WAN-Schnittstelle bei der NanoStation brauchen. Anstatt Freifunk-lan sollte ein Uplink angeschlossen werden.

Ist es sinnvoll eine "leere WAN-Schnittstelle" anzulegen, um solche Umkonfigurationen mher intuitiv zu machen?
ein passendes UCI-default-script sollte da ja ausreichen.

**Comment by sarumpaet** [comment]
Ich sehe jetzt nicht ganz, wieso wir da für sowieso ggf. nötige manuelle Konfiguration in den Skripten Vorarbeit leisten sollten. Das ist besser mit Doku zu erledigen.

Eine saubere (Code-)Lösung wäre, den Benutzer beim Setup auswählen zu lassen, was er an welchem Port haben möchte; das würde nebenbei auch Mesh-on-LAN-Setups deutlich vereinfachen, da man sowas sagen könnte wie "LAN0 = Uplink; LAN1 = Freifunk Mesh; LAN2 = Freifunk Client-DHCP" und so weiter.

Ich schließe das hier mal, weil es eigentlich schon https://github.com/freifunk-berlin/firmware/issues/292 für dieses Thema gibt.
