### ISSUE TITLE
ffwizard: setup of Private Access Point required to pass dialog

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/firmware#427]
```
 Firmware Berlin (Hedy 0.3.0-alpha rev eab0343)
 Generic - ramips/rt305x
```
This is the self-compiled software, without vpn.
When I access the GUI, Freifunk-assistent, I am required to type in a private access point password even when I do not make a tick at "private access point".
I would expect to not see and need to do anything when the private access point option is not chosen.

(The only password that worked for me was "00000000")
![image](https://cloud.githubusercontent.com/assets/564768/23579236/52431104-00e9-11e7-8cf5-008fa96296a1.png)

**Comment by SvenRoederer** [comment]
Thanks for opening this issue. I've seen this already an noted in #418 .

It must relate to updated codebase of LuCI, that comes with the current LuCI-feed.

**Comment by SvenRoederer** [comment]
I vote for removing this private AP feature at all, as once discussed in #143 .

**Comment by SvenRoederer** [comment]
@niccokunzmann I reverted some commits to exclude the AP-feature again.
CAn you please try https://buildbot.berlin.freifunk.net/buildbot/unstable/mpc85xx-generic/143/packages/packages/powerpc_8540/packages_berlin/luci-app-ffwizard-berlin_0.0.6-1_all.ipk

**Comment by niccokunzmann** [comment]
@SvenRoederer What can I do with the ipk file?
I would expect to pull and checkout a git commit to test changes.

**Comment by SvenRoederer** [comment]
@niccokunzmann hope you have a spare-router, where you can upgrade this ffwizard-package and then start the configuration.

you can for sure compile by yourself, just follow the branch the mentioned commit belongs to.

**Comment by SvenRoederer** [comment]
see PR https://github.com/freifunk-berlin/firmware-packages/pull/107 to remove this code

**Comment by booo** [comment]
We removed the private ap code as discussed early.
