### ISSUE TITLE
Feeds of OpenWrt instead of Lede?

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/firmware#429]
I recognized that the current version of the firmware uses LEDE but some of the [feeds](https://github.com/freifunk-berlin/firmware/blob/master/feeds.conf#L1) still use OpenWrt.

I assume, they should be moved, too. Is that so?

**Comment by SvenRoederer** [comment]
check within LEDE: https://git.lede-project.org/?p=source.git;a=blob;f=feeds.conf.default;h=040dbdc551f209277778336b422e70b3b168cfe0;hb=HEAD

**Comment by niccokunzmann** [comment]
It looks like they are the same.

**Comment by niccokunzmann** [comment]
Should I create a pull-request?

**Comment by SvenRoederer** [comment]
correct, feeds are shared between both projects.
A PR for what? Do you miss a special feature, that was introduced recently?

**Comment by niccokunzmann** [comment]
I thought that since the firmware runs on LEDE now, some inconsistencies may be there and should have to be ported. Since this is none of them, I close the issue. Thanks for the clarification!
