### ISSUE TITLE
ff-assistent: shows textbox with OpenVPN-key paths inside

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#437]
with Updated LuCI of 2017 the ffwizard shows the following screen when uploading the VPN-keys
![ffwizard-vpn-keys_inputbox](https://cloud.githubusercontent.com/assets/1755362/24085242/78d58fca-0cf8-11e7-8db3-611edcebc39c.png)

These Inputboxes should be invisible as in previous releases

**Comment by SvenRoederer** [comment]
I feel like I saw this in the "luci-app-openvpn" also. So this seems a generic behavior and not considered as a bug.
Any opinions?

**Comment by bobster-galore** [comment]
It seems to be an upstream problem. We watch it?! postponed to 1.1.0?

**Comment by SvenRoederer** [comment]
these additional textboxes can also bee seen in the luci-app-openvpn page.
So it might be a wanted thing from upstream.
![luci-app-openvpn](https://user-images.githubusercontent.com/1755362/31796803-8aa49efe-b52b-11e7-8dc7-32d13b15f56e.png)

**Comment by bobster-galore** [comment]
I postpone it until we drop it.

**Comment by SvenRoederer** [comment]
yeah, let's wait for users feedback with Hedy-1.0.0 on this and then decide if we just close or a change is required
