### ISSUE TITLE
Lede Build - 5Ghz not enabled

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#441]
After running the wizard on a fresh install, the 5Ghz radio is not enabled.

Target platform: wdr3600
Build: Freifunk Berlin Hedy 1.0.0-routing-master-alpha 403c57e r3205-59508e3

**Comment by booo** [comment]
I can confirm this problem.

I will try to take a look and maybe move the wifi specific code out of the wizards.

**Comment by booo** [comment]
Inspiration for reworking the wifi setup code:

https://github.com/freifunk-berlin/firmware-packages/blob/master/utils/freifunk-berlin-wizard-backend/files/usr/lib/ffwizard.d/15-wireless.sh

https://github.com/freifunk-berlin/firmware/issues/293

Maybe we should rework the upstream code so we can use it as library for our setup process:

https://github.com/lede-project/source/blob/079d57b0f290a79c9dbc013b6e9c83cebf8a2f99/package/kernel/mac80211/files/lib/wifi/mac80211.sh

**Comment by booo** [comment]
I suggest that we merge the referenced pull request and rework the wifi setup code another day.

**Comment by booo** [comment]
Actually this is caused by the freifunk config creation problem described in this ticket: https://github.com/freifunk-berlin/firmware/issues/438

**Comment by booo** [comment]
Should work again.
