### ISSUE TITLE
Lede Build - OLSR6 fails

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#443]
Build: Freifunk Berlin Hedy 1.0.0-routing-master-alpha 403c57e r3205-59508e3

After updating the plugin versions to the correct ones, starting olsr6 fails

daemon.err olsrd[7189]: olsrd exit: -- PLUGIN LOADING FAILED --

**Comment by booo** [comment]
@pmelange Can you provide us with a bit more information? Maybe run olsrd by hand from the commandline and post the error log?

**Comment by pmelange** [comment]
@booo I don't have any test devices right now.  I'll try to get one in the next few days and post the results when I have them.

**Comment by booo** [comment]
I think the referenced commit solves the problem.

**Comment by pmelange** [comment]
The commit works with both the 1.0.0-olsrd0903-alpha branch and the SAm0815_Hedy-alpha_routing-master branch.

@SvenRoederer Do you want to merge this commit to the SAm0815_Hedy-alpha_routing-master branch?

**Comment by booo** [comment]
If the commit works we should merge this into the master branch. I will do so if there is no objection till the end of the week.

**Comment by booo** [comment]
Merged.
