### ISSUE TITLE
Lede Build - OLSR status pages are not showing correct data

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#444]
The luci status page for configured interfaces does not show the actual data.
The luci status page for the smart gateway shows nothing although the plugin definately sets up a tunnel correctly.

Running a command such as 'echo "/gateways" | nc 127.0.0.1 9090' is not nicely indented and organized like it is in 0.2.0. There is also some new information provided by this command. Perhaps that is having in influence on the luci status pages.

**Comment by bobster-galore** [comment]
Did u see that in recent builds? I checked:
http://lynar-luther.olsr/cgi-bin/luci/freifunk/olsr/smartgw which is ok to me. And at
http://chris-core.olsr/cgi-bin/luci/freifunk/olsr/smartgw which is 0.3.0 and no gw is selected albeit it is working on a smartgw.

**Comment by bobster-galore** [comment]
any new observations? Shall we postpone to Hedy-1.1.0

**Comment by SvenRoederer** [comment]
in 1b45bfce I added a patch to switch back to olsrd 0.9.0.3 in the openwrt-routing feed.
This patch also includes reverting the changes in LuCI regarding ETX-calculation

**Comment by bobster-galore** [comment]
Is this still unsolved? Can we close this?

**Comment by pmelange** [comment]
Seems to be solved
