### ISSUE TITLE
remove strict binding to VPN03

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#455]
As VPN03 will disappear soon, we should
- make the firmware compatible to use no VPN
- make an easy way to use other VPN-services

same should be implemented in the wizard

**Comment by bobster-galore** [comment]
Is'nt it already done? I recall working with it.

**Comment by SvenRoederer** [comment]
merged with https://github.com/freifunk-berlin/firmware-packages/commit/359c074b23dcf4e85d2884550f15638e6b2c794c on 28. Aug.2017
