### ISSUE TITLE
wifi on after flash

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/firmware#479]
wifi enabled after flash would be really nice, to have a second possibility to connect to the router for configuring. I think security concerns are neglectable because I presume routers are configured in one go. So there's not that much time to capture the router while configuration.
How u mean?

**Comment by booo** [comment]
Normally you can enable the wifi by pressing the wifi button.

**Comment by SvenRoederer** [comment]
I've seen routers around, which do not have a wifi-button or any other button.

**Comment by bobster-galore** [comment]
3 of 5 of my routers don't have a wifi-button.
The next generation CPE-210 will have only one port so there's no wifi button and no dhcp on a port.

**Comment by bobster-galore** [comment]
Is withdrawn after community-discussion https://lists.berlin.freifunk.net/pipermail/berlin/2017-October/036443.html
