### ISSUE TITLE
wizard-backend: openvpn files have underscores instead of hyphens

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#481]
The `json_get_keys` function in lede translates hyphens to underscores. This breaks openvpn configs where options with hyphens are used (for example `auth-user-pass`).

Ideally we'd only use `jsonfilter` but it doesn't seem to support extracting of all keys of an object (or iterating over key-value pairs). So perhaps it's easier to fix `json_get_keys`. :)

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
