### ISSUE TITLE
wizard-backend: jsonrpc/ubus/ubox fail to parse json with certain tunnel configs

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#482]
ubus chokes on config.json files with certain tunnel configs (e.g., VPN03 configs). Everything runs smoothly if the `config.json` is transferred manually to the router and then applied with `ffwizard_apply`.

It's probably the same issue that prevents us from using ubus for firmware upgrades.

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
