### ISSUE TITLE
wizard-backend: add firmware upgrade script

### ISSUE THREAD

**Issue by andrenarchy** [freifunk-berlin/firmware#484]
Sending the firmware as a base64-encoded string via rpcd is cumbersome and may even lead to OOM on low-memory devices. Currently the HTTP request fails anyway.

As a solution to this problem we can add a tiny cgi script that accepts binary files in the HTTP request's body and pipes them to the filesystem. Of course the request must be authenticated with a valid rpcd session.

**Comment by SvenRoederer** [comment]
As nobody is interested in working on the wizard2-code, it was agreed to be removed from the repo (see https://github.com/freifunk-berlin/firmware/issues/746#issuecomment-624242172). As a consequence we also close all relating issues.
