### ISSUE TITLE
Luci doesn't show 802.11s correctly in /luci/admin/network/wireless

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/firmware#496]
It doesn't show correct status, it's deactivated or smthg. Is the status not determinable?
Meshid isn't shown instead of ssid. May be the table-header can be changed to ssid / meshid in second column?
s.a. https://github.com/openwrt/luci/issues/1228#issuecomment-337924706

**Comment by SvenRoederer** [comment]
An issue has been opened upstream: https://github.com/openwrt/luci/issues/1512

let's track it there and close this
