### ISSUE TITLE
SAm0815_Hedy-alpha: mesh working but no internet

### ISSUE THREAD

**Issue by lightcatcher** [freifunk-berlin/firmware#502]
setup: ubnt-erx (uplink) ---lanmesh---wdr3600()-+-+wifi-mesh-+-+nanostation-m2
firmware:

- ubnt-erx: 493-vpn03-freifunk-berlin-1.0.0-alpha-sam0815-43478e9-ramips-mt7621-ubnt-erx-squashfs-sysupgrade.bin

- wdr3600: 572-freifunk-berlin-1.0.0-alpha-sam0815-43478e9-tl-wdr3600-v1-sysupgrade.bin

- nano m2: 572-freifunk-berlin-1.0.0-alpha-sam0815-43478e9-ubnt-nano-m-sysupgrade.bin

no internet at nanostation via lan+wifi, mesh works till wdr3600 (incl. webinterface)
ping from device to lede-project.org gives "bad adress"
log from after setup +reboot in the attachment

UPDATE: flashed the nano m2 today with kathleen 0.3.0 build, same issue with the setup.
So it seems the source of the problem might be on the wdr3600 ? what do you think ?

[no internet-nano-m2.txt](https://github.com/freifunk-berlin/firmware/files/1589058/no.internet-nano-m2.txt)

**Comment by SvenRoederer** [comment]
* Is the NSM seeing the OLSR-neighbours?
* what's the output of ```ip route get 8.8.8.8```?

**Comment by lightcatcher** [comment]
NSM sees the wdr3600 in olsr neighbours

root@berlinerstr-tegel-m2-2:~# ip route get 8.8.8.8
8.8.8.8 dev tnl_0a1f0057  src 10.31.15.28 
    cache 
-----

**Comment by lightcatcher** [comment]
now working with Hedy-1.0.0-rc1.
