### ISSUE TITLE
"diff" tool missing in packages

### ISSUE THREAD

**Issue by torte71** [freifunk-berlin/firmware#505]
https://buildbot.berlin.freifunk.net/buildbot/unstable/ar71xx-generic/576/VERSION.txt
Firmware: git branch "SAm0815_experimental", revision 1ddb59a

I want my "diff" back :)

`diff network.bak network`
`-ash: diff: not found`

`opkg update && opkg search "*diff*"`
`[ no results ]`

Would be nice to have at least an opkg-installable package.

**Comment by SvenRoederer** [comment]
it has never been here, but you can find the ```diffutils``` in the packages feed.
so you can install from the original LEDE-repo or send PR to enable in our builds

**Comment by SvenRoederer** [comment]
will you do a PR for this?

**Comment by torte71** [comment]
OK. I'll add diffutils and patch as optional packages (i.e. not included in the images).
Will a single PR for "head" suffice? It would apply (with fuzz) and work with rc1 and experimental as well.
