### ISSUE TITLE
Hedy-1.0.0-rc1: olsrd SIGSEV when network is restarted

### ISSUE THREAD

**Issue by torte71** [freifunk-berlin/firmware#513]
Seen on GL-AR150 / Freifunk Berlin Hedy 1.0.0-rc1 5c1dc9d
Seen on WR842v3 / Freifunk Berlin Hedy 1.0.0-rc1 732db7e

After "/etc/init.d/network restart", two SIGSEVs from the olsrd processes show up.
The olsrd processes (for v4 and v6) get restarted automatically, so the routers still seem to work fine afterwards.

```
do_page_fault(): sending SIGSEGV to olsrd for invalid write access to 00468ab8
[  146.006044] epc = 00417249 in olsrd[400000+38000]
[  146.010582] ra  = 0041dc4f in olsrd[400000+38000]
[  146.015254]
[  150.139164]
do_page_fault(): sending SIGSEGV to olsrd for invalid write access to 00000000
[  150.146120] epc = 77598638 in libc.so[77570000+92000]
[  150.151012] ra  = 004180ad in olsrd[400000+38000]
[  150.155697]
```

Hedy 1.0.0-rc1 5c1dc9d on GL-AR150:
```
root@torte-ar150:~# olsrd --version

 *** olsr.org - 0.9.0.3-git_dca4dfa-hash_918e3f695a68a99288440860eb8cad6e ***
 Build date: 2018-01-07 19:04:16 on buildbot
```

Hedy 1.0.0-rc1 732db7e on WR842v3:
```
root@skkr842-1:~# olsrd --version

 *** olsr.org - 0.9.0.3-git_f033697-hash_c7f667fe7cf42baa389872842561b6c3 ***
 Build date: 2018-01-17 12:57:06 on ubuntu
```

Not seen on experimental branch (Freifunk Berlin 1.1.0-alpha-SAm0815 819a34e):
```
root@wr842-1:~# olsrd --version

 *** olsr.org - 0.9.6.2-git_9c2ac19-hash_304b14af812f6f63e9ef6104836fb11f ***
 Build date: 2018-01-19 23:30:16 on ubuntu
```

**Comment by SvenRoederer** [comment]
Afair this is related to an incompatibility of olsrd-0.9.0.3 with lib musl. Probably fixed by https://github.com/OLSR/olsrd/commit/40993f39efbb20be7094314ab418c2606d51871b.

But as it's only on shutdown of the daemon, I never felt that this is important enough to fix. As in general we shout go forward an start implementing olsrd-0.9.6+ .
