### ISSUE TITLE
add support for GL-inet GL-MT300N-V2

### ISSUE THREAD

**Issue by booo** [freifunk-berlin/firmware#519]
Add support for GL-inet GL-MT300N-V2 and build target.

https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=abbfcc85259a4f6658c61e99dd3d2d3567e3eb3a

**Comment by SvenRoederer** [comment]
please see https://github.com/freifunk-berlin/firmware/commit/c9cace397039b90c693f32054ecffa943b1aa203#diff-9509504bd5ec1a3192f1dc26d0108cb4, which also adds TpLink WR841-v13.

only needs updated buildbot.

**Comment by SvenRoederer** [comment]
will be added with PR https://github.com/freifunk-berlin/firmware/pull/526
