### ISSUE TITLE
New board: ramips-mt7621 ew1200

### ISSUE THREAD

**Issue by nExXxuS** [freifunk-berlin/firmware#521]
Could you please build experimental builds for target ew1200 on ramips-mt7621? Unfortunately i'm unable to get successfull builds. Best Simon

**Comment by SvenRoederer** [comment]
added with 4dbcaa6387e82ccf40858314d34bdc3a259aa030 to SAm0815_experimental branch

**Comment by nExXxuS** [comment]
Current HEAD works perfect fine and stable on 2,4GHz and 5GHz both in following setup:
https://wiki.freifunk.net/Berlin:Standorte:WilhelmGuddorf10

Thanks a lot!

Thanks a lot.

**Comment by SvenRoederer** [comment]
please have in mind to regularly check for updated code
