### ISSUE TITLE
unexpected results configuring mesh (11s)

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/firmware#539]
I experienced unexpected results when configuring mesh (11s).
I entered mesh_id and ip when the configuration was not completed. There were lines missing in the configuration that I had to complete manually.
Just for the records, if it happens again / regularly?

**Comment by SvenRoederer** [comment]
Can you be a bit verbose on the steps you did?

**Comment by booo** [comment]
We need more information.

If you used the administration interface I guess it's an upstream problem.

I'm closing this ticket because of the missing information and time passed without reply.
