### ISSUE TITLE
OLSR crashes but leaves an unkillable zombie process

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#540]
I have had the following happen to me three time since installing the firmware on an ERX-SFP (Hedy 1.0.0).

OLSR crashes and there is nothing I can do to restart it.  If I run the neigh.sh script, it hangs.  If I run /etc/init.d/olsrd restart, it hangs.  If I kill -9 the PID, the process stays in the ps list.

The folowing kernel message is shown every 5 to 10 seconds:
```
kern.emerg kernel: [1054204.339802] unregister_netdevice: waiting for tnl_010b1f0a to become free. Usage count = 1
```

And when the OLSR watchdog runs, I get:
```
cron.info crond[1532]: USER root pid 26254 cmd /usr/sbin/ff_olsr_watchdog
daemon.err olsrd: /etc/init.d/olsrd: ERROR: there is already an instance of olsrd running (pid: '10264'), not starting.

Since killing the process doesn't work, the only other alternative is to reboot the device.

**Comment by pmelange** [comment]
There is a clear change in memory usage too.


![screenshot_2018-04-02_00-52-13](https://user-images.githubusercontent.com/20710446/38178313-6d4a403c-3610-11e8-83cc-e8cad7cca571.png)

**Comment by SvenRoederer** [comment]
as mentioned by the olsrd-maintainers, we should upgrade to olsr 0.9.6.1+ (https://github.com/freifunk-berlin/firmware/issues/424#issuecomment-287652084)

**Comment by bobster-galore** [comment]
... and u can't kill a zombie since it's already dead!
U might kill everything above and around it, to let the zombie rest in piece.

**Comment by pmelange** [comment]
This has happened to me 4 more times since I wrote this issue.  I am going to replace the ERX-SFP with a WDR4900 to see if the problem persists.  

@bobster-galore silly

**Comment by pmelange** [comment]
This was only a problem with the ERX-SFP

**Comment by SvenRoederer** [comment]
what caused this on your ERX?

**Comment by pmelange** [comment]
Unknown.  The ERX is not longer being used with openwrt.  All the info I had I put in the original comment
