### ISSUE TITLE
Profiles: Remove DNS-Server 213.73.91.35

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#551]
The DNS server 213.73.91.35 is offline.  It is set in many of the profiles and needs to be removed.

https://twitter.com/clubdiscordia/status/983109445784875009?s=11

**Comment by pmelange** [comment]
openwrt/luci#1757

**Comment by pmelange** [comment]
Pull Request openwrt/luci#1759

**Comment by pmelange** [comment]
PR: hnyman merged commit 0c30ee0 into openwrt:master

**Comment by booo** [comment]
We should find a replacement for the old one.

The ip is still in the olsrd configuration:

 https://github.com/freifunk-berlin/firmware-packages/blob/master/defaults/freifunk-berlin-olsrd-defaults/uci-defaults/freifunk-berlin-olsrd-defaults#L44

**Comment by pmelange** [comment]
Yes, we should find a new one.  A new nameserver should go in its own issue/pr.

The host still responds to pings.  There is no problem with it being in the olsrd ping list

**Comment by booo** [comment]
Is there a issue for a new nameserver? Can you create one if there is no issue?

We should not assume that the host stays online and should remove it from the ping list or better replace it.

**Comment by pmelange** [comment]
New issue created for a new potential nameserver #552

**Comment by SvenRoederer** [comment]
just requested a cherry-pick into lede-17.01 branch (https://github.com/openwrt/luci/issues/1760).

we also need a migratioin for the DNS-server list

**Comment by booo** [comment]
This pull request includes a migration script: https://github.com/freifunk-berlin/firmware-packages/pull/152

**Comment by SvenRoederer** [comment]
https://github.com/freifunk-berlin/firmware-packages/commit/212db23968edc8bcc5302e9a08a2c51d97490aa0 adds a migration for Hedy-1.0.2

**Comment by pmelange** [comment]
Maybe this should be run with every migration. Sort of a standard thing to do, always set the DNS servers. https://github.com/freifunk-berlin/firmware-packages/blob/ea6d78598a3edf4daca5c72208946364b7d1b136/utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh#L443-L452

**Comment by SvenRoederer** [comment]
master: 
migration: https://github.com/freifunk-berlin/firmware-packages/commit/a2156221f511e4ee4283323dc4b68103b04010bd; profile: https://github.com/openwrt/luci/commit/c2d3fe8a9730a519278def5534c60ee6991185c3#diff-3faaef5bc5179c8442a73059db372a80
V1.0.2:
migration: https://github.com/freifunk-berlin/firmware-packages/commit/212db23968edc8bcc5302e9a08a2c51d97490aa0; profile: https://github.com/openwrt/luci/commit/09ae638e4b4eb6ee11fd718caf209c6c983a6e0e#diff-3faaef5bc5179c8442a73059db372a80
