### ISSUE TITLE
Build dependency error when on gcc/g++ 8

### ISSUE THREAD

**Issue by mophahr** [freifunk-berlin/firmware#557]
Compiling doesn't work on gcc/g++ version larger than 7 because the check `-dumpversion | grep -E '(4\.[8-9]|5\.?[0-9]?|6\.?[0-9]?|7\.?[0-9]?)` in `openwrt/include/prereq-build.mk` only goes up to 7.x

**Comment by SvenRoederer** [comment]
* which branch have you used?
*  have you tried branch "SAm0815_experimental"?

**Comment by mophahr** [comment]
I am on master and I haven't tried "SAm0815_experimental" yet.

**Comment by SvenRoederer** [comment]
SO this might also get fixed by https://github.com/freifunk-berlin/firmware/issues/558#issuecomment-390323737

**Comment by SvenRoederer** [comment]
should be fixed in master. Feel free to reopen if it still fails.
