### ISSUE TITLE
Use UPX to reduce executable file sizes

### ISSUE THREAD

**Issue by kriegste** [freifunk-berlin/firmware#563]
Have you tried UPX to reduce the sizes of executable files? This might help fitting new version into 4MB models.

I tried with a few files from /usr/bin and /usr/sbin from my router. They were not compressed previously and compression rate was about 50%.

https://upx.github.io
https://github.com/upx/upx

**Comment by torte71** [comment]
The filesystem is a lzma compressed squashfs. Recompressing already compressed data usually doesn't give any advantages.

**Comment by kriegste** [comment]
Ah, ok, I thought it was uncompressed.
