### ISSUE TITLE
actual failsafe doc link in failsafe mode

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/firmware#572]
The documentation link in failsafe mode should point to https://openwrt.org/docs/guide-user/troubleshooting/failsafe_and_factory_reset .
http://wiki.openwrt.org/doc/howto/generic.failsafe is deprecated.

**Comment by SvenRoederer** [comment]
I don't get it ??????

**Comment by bobster-galore** [comment]
If u are in failsafe mode on ur router there is a link for more information on failsafe mode, which is deprecated.

**Comment by SvenRoederer** [comment]
is it showing the freifunk banner or a openwrt banner?

**Comment by booo** [comment]
https://git.openwrt.org/?p=openwrt/openwrt.git;a=blob;f=package/base-files/files/etc/banner.failsafe;h=14615e1ef7a08213157f295118fd2a31fb2e502d;hb=HEAD

Could you please file this upstream?

**Comment by bobster-galore** [comment]
Done. https://github.com/openwrt/packages/issues/6282

**Comment by SvenRoederer** [comment]
fixed upstream for master, 18.06 and 17.01 branches
