### ISSUE TITLE
migration for updated olsr-defaults missing

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#574]
for https://github.com/freifunk-berlin/firmware-packages/commit/4d439e24524ccad1e9c25362e905bb07eaf6cd2e of branch olsrd-pluginnames we need to create a migration.

**Comment by bobster-galore** [comment]
Put it there https://github.com/freifunk-berlin/firmware-packages/blob/olsrd-pluginnames/utils/freifunk-berlin-migration/uci-defaults/freifunk-berlin-01-migration.sh

**Comment by SvenRoederer** [comment]
Thanks, but this will not change the olsr6 config, right?

**Comment by bobster-galore** [comment]
olsrd6 is included now.

**Comment by SvenRoederer** [comment]
checked on one of my test-nodes - works as expected.
Merged in https://github.com/freifunk-berlin/firmware-packages/commit/2cf038544234495984dce8c3a644401b2b78a295
