### ISSUE TITLE
How can we integrate alphas etc. if we know a little about the version?

### ISSUE THREAD

**Issue by bobster-galore** [freifunk-berlin/firmware#590]
Where could something like
firmware |  
-- | --
name | "Freifunk Berlin 1.1.0-alpha"
revision | "0fc1f81"
could be showed in
https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net/blob/master/owm2ffmap/owm2ffmap.py
?
instead of unknown/unknown?

**Comment by SvenRoederer** [comment]
This should be addressed in a ticket under https://github.com/freifunk-berlin/hopglass.berlin.freifunk.net.
As the visualization is done by "parse_firmware(firmware)"
