### ISSUE TITLE
The OLSR services are not working

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#594]
Tested with Freifunk Berlin 1.1.0-alpha 4155686 (tunnel-berlin) on a WR842v3

The "Services" menu option on the top of the web interface is not there.  It should be between Statistics and Map.  

Manually entering the address http://frei.funk/cgi-bin/luci/freifunk/services give a 404 Not Found.

**Comment by pmelange** [comment]
The nameservice plugin is active and the contents of /var/etc/services.olsr looks to be correct.

**Comment by mmouselli** [comment]
The problem has been fixed, you need to update Freifunk's repositories.
https://github.com/openwrt/luci/pull/2238

**Comment by booo** [comment]
Fixed with merge https://github.com/openwrt/luci/commit/290610798a4d6ced5d0db31e1cbcad7d758e020f

Once we update the luci feed this should be fixed.

**Comment by SvenRoederer** [comment]
@booo but have in mind, that this is only in the master-branch for now

**Comment by booo** [comment]
The olsrd library version numbers are everywhere. I created a pull request to get rid of every version number in the code.
