### ISSUE TITLE
the README.md often points to outdated pages (of OpenWrt)

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#597]
Since the remerge of LEDE and OpenWrt some of the infrastructure has changed and was replaced by new instances.
Our README.md file still links to the historic pages. These are at least:
* the Wiki-pages
* the development pages

**Comment by bobster-galore** [comment]
What could be keywords to extract a list from github what to alter?

**Comment by SvenRoederer** [comment]
I just read the text and found some. At least the wiki-pages need do be checked for the current counterparts.
Some improvment are in https://github.com/freifunk-berlin/firmware/pull/598, https://github.com/freifunk-berlin/firmware/pull/599

**Comment by SvenRoederer** [comment]
I assume this was autocolsed somehow
