### ISSUE TITLE
No Uplink for Clients - missing ffuplink interface

### ISSUE THREAD

**Issue by Akira25** [freifunk-berlin/firmware#604]
Tested with the master branch.

The issue is that sometimes the ffuplink and ffuplink_wan devices are not created.  This is because of the macaddress which is being generated in firmware-package/uplink/freifunk-berlin-no-tunnel-files/uci-default/freifunk-berlin-notunnel and in the migration script.

The macaddress generation part of the scripts correctly flips the U/L bit to 1, which is what we need.  Unfortunately the script does not set the LSB bit to 0.

The result is that an invalid mac address may be created, which prevents the ffuplink and ffuplink_wan interfaces from going up.

Recommendation is to reverse commit https://github.com/freifunk-berlin/firmware-packages/commit/4b379d3ea8af4fd70e62ede301ded69c92f95c4a

**Comment by pmelange** [comment]
This has been fixed in https://github.com/freifunk-berlin/firmware-packages/pull/147
