### ISSUE TITLE
tunneldigger config change, bind to interface

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#606]
This applies to both ffuplink and bbbdigger.

If the node is not connect to wan, but meshes, tunneldigger will attept to build the tunnel though another the smart gw.  This creates an undesired loopback.  The solition is to add ```option bind_interface 'wan'```.

Changing the option solves this problem  But leads to another.  Even though the wan interface is not up, tunneldigger tries to connect.  This produces a lot of log entries.  

I see two pssible solutions.   [Edit, see below]

**Comment by pmelange** [comment]
There is an issue at https://github.com/wlanslovenija/tunneldigger/issues/84

**Comment by booo** [comment]
Please add a hotplug script that starts/stops the tunneldigger service. We did the same for openvpn.

**Comment by pmelange** [comment]
OK.  So now the question is, should we keep using and patching the gluon tunneldigger (it is just a Makefile, initscript, and sample config file). Or should we just make our own tunneldigger package.

The gluon script grabs the source code from wlanslovenia.  We could do that just as easily.

Where would our version of tunneldigger go?  in firmware-packages/utils, firmware-packages/addons or firmware-packages/defaults?  Will the build env always take our tunneldigger package over the one from gluon?  Or should we name it freifunk-berlin-tunneldigger to aviod any conflicts?

**Comment by pmelange** [comment]
I have a rewritten init script and a functioning hotplug script.

I'm still not sure how to package this into the firmware.  Here are my ideas:
1) Update the patch https://github.com/freifunk-berlin/firmware/blob/master/patches/101-tunneldigger_init.patch
2) Create a package similar to how freifunk-gluon does it (basically a makefile which pulls the tunneldigger code, builds the client, then adds the specialized init and hotplug script)? https://github.com/freifunk-gluon/packages/blob/master/net/tunneldigger/Makefile
3) Create a freifunk-berlin-tunneldigger-default package which contains only the init and hotplug files. (Will this properly overwrite the init script from gluon)?

All of these options do not force us to fork tunneldigger.

**Comment by booo** [comment]
Can you upload your work somewhere and reference it here?

Why do you have to rewrite the init script?

The hotplug script can be part of this package https://github.com/freifunk-berlin/firmware-packages/tree/master/uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files and this package https://github.com/freifunk-berlin/firmware-packages/tree/master/addons/freifunk-berlin-bbbdigger as far as I can tell.

**Comment by pmelange** [comment]
The new init script is https://github.com/pmelange/Temporary-Files/blob/master/tunneldigger.init
The new hotplug script is https://github.com/pmelange/Temporary-Files/blob/master/tunneldigger.hotplug

The init script and the hotplug script are written to be independent of the tunnel (uplink-tunnelberlin-tunneldigger or bbbdigger or whatever).

The changes to the init script are:
* do not start a tunnel if an interface is defined by the bind_interface option.
* move the tunnel_id increment to the top of the handle_td function.

The hotplug script:
* brings up a tunnel if the interface goes up and is defined by the bind_interface option
* brings down a tunnel if the interface goes down and is defined by the bind_interface option

I would not add this to either uplink-tunnelberlin-tunneldigger or bbbdigger.  These belong with the tunneldigger package.

**Comment by pmelange** [comment]
This seems to new be intergrated properly.  closing
