### ISSUE TITLE
Luci feed: the web interface to opkg is now it's own package 

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#621]
luci-mod-system no longer does opkg management. It has been split out into a new package called luci-app-opkg.  The upstream commit is openwrt/luci@aa2e0e2

Should we add luci-app-opkg to common.config or make it a dependency of luci-mod-freifunk-ui?

**Comment by booo** [comment]
Does luci-mod-freifunk-ui need the package to work or is it more of an optional plugin? If it's optional please add it to the common.config

**Comment by pmelange** [comment]
luci-mod-freifunk-ui does not __need__ the new luci-app-opkg.  I'll get a PR out with the changes soon (common.config and all the files in the packages directory).

**Comment by SvenRoederer** [comment]
fixed with 0f9db4f751505ab7591c78bd3de35cf6623b0dcd
