### ISSUE TITLE
Wiko device can not connect to AP

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#635]
Device can not connect to AP.
Device can do an association but instantly gets kicked again.

    Sun Dec  9 11:02:39 2018 daemon.info hostapd: wlan0-dhcp-5: STA c8:3c:XX:XX:XX:XX IEEE 802.11: authenticated
    Sun Dec  9 11:02:39 2018 daemon.info hostapd: wlan0-dhcp-5: STA c8:3c:XX:XX:XX:XX IEEE 802.11: associated (aid 2)
    Sun Dec  9 11:02:39 2018 daemon.notice hostapd: wlan0-dhcp-5: AP-STA-CONNECTED c8:3c:XX:XX:XX:XX
    Sun Dec  9 11:02:39 2018 daemon.info hostapd: wlan0-dhcp-5: STA c8:3c:XX:XX:XX:XX RADIUS: starting accounting session B9D894F5363AE4E3
    Sun Dec  9 11:02:40 2018 daemon.notice hostapd: wlan0-dhcp-5: AP-STA-DISCONNECTED c8:3c:XX:XX:XX:XX
    Sun Dec  9 11:02:40 2018 daemon.info hostapd: wlan0-dhcp-5: STA c8:3c:XX:XX:XX:XX IEEE 802.11: disassociated
    Sun Dec  9 11:02:41 2018 daemon.info hostapd: wlan0-dhcp-5: STA c8:3c:XX:XX:XX:XX IEEE 802.11: deauthenticated due to inactivity (timer DEAUTH/REMOVE)

Information:
* Archer C7 v2
*  Freifunk Berlin Hedy 1.0.1 v1.0.1 / LuCI lede-17.01 branch (git-18.056.25406-c1e6a3d) 
* Client: Wiko pulb fab 4g
* Android 5.1.1

### Problem
Disassociation on low ack is not working correctly on 5 GHz.

### Work Around
Go to ``/etc/config/wireless`` and add ``disassoc_low_ack '0'`` to 5 GHz interface

### Guess
``ath10k`` is not working with the option ``disassoc_low_ack`` correctly?

### Solution
Disable  ``disassoc_low_ack`` with 5 GHz devices.
Can we add some patch that adds the option ``disassoc_low_ack '0'`` if a driver uses ``ath10k``?
Or is ``disassoc_low_ack`` very important?

Pull Request:
* https://github.com/freifunk-berlin/firmware-packages/pull/165

### Related Posts
* https://forum.openwrt.org/t/solved-deauthenticated-due-to-inactivity-after-seconds/16294
* [Gluon had some problem](https://github.com/freifunk-gluon/gluon/issues/1317)

**Comment by PolynomialDivision** [comment]
Ok I have the solution.
Add to ``/etc/config/wireless`` to the interfaces...

    option disassoc_low_ack '0'

Related Openwrt Forum Post:
* https://forum.openwrt.org/t/solved-deauthenticated-due-to-inactivity-after-seconds/16294

**Comment by pmelange** [comment]
What is the effect on routers which do not have this issue.  Are there any drawbacks to using this setting?

**Comment by PolynomialDivision** [comment]
> What is the effect on routers which do not have this issue. Are there any drawbacks to using this setting?

I'm not sure. But the gluon thread said that upgrading to a nightly openwrt version can work.
Can somebody build a freifunk version with nightly openwrt version for archer c7 v2?

**Comment by SvenRoederer** [comment]
@PolynomialDivision as the buildbot is running again, we get "nightly openwrt" based build of openwrt-19.07 and openwrt-master. Have a look at https://github.com/freifunk-berlin/firmware/wiki#the-official-branches-are to identify the branch you are looking for.
