### ISSUE TITLE
Hedy-1-0-2-dev: change uplink to tunnel-berlin (openvpn) does not work.

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#637]
This is tested with build b76e14d

When starting with either default or tunnel-berlin-tunneldigger, and performing an update to tunnel-berlin (openvpn) the following occurs:

* /etc/config/openvpn is not configured (original setting from openvpn are there, complete with comments)
* <strike>/etc/config/ffwizard` does not exist</strike> EDIT: after testing a second time, this file is fine

This may be related to #636

**Comment by pmelange** [comment]
When manually running the openvpn configuration file, the following happens:
```
/rom/etc/uci-defaults# sh ./freifunk-berlin-z90_openvpn 
uci: I/O error
uci: Entry not found
uci: Entry not found
uci: Entry not found
```

**Comment by SvenRoederer** [comment]
as it seems to be related to https://github.com/freifunk-berlin/firmware/issues/636, have you retested this this issue also? Probably it's also gone ...

**Comment by pmelange** [comment]
I tested it again today with b76e14d.  It still is an issue.  The contents of /etc/config/openvpn are wrong.  I am building with commits 3db977714bc7870e777c4b15cf974ddc9242f5d4 and d4b765df0c22197df5facbfea76833724462e43d.  When I have tested, I will post

**Comment by pmelange** [comment]
@SvenRoederer 
I think I found the problem.  The function guard has an exit in it.  Maybe it should just return.

**Comment by pmelange** [comment]
I think I found another problem.  The script /rom/etc/uci-defaults/freifunk-berlin-z90_openvpn is not executable.  We need to call it with sh.
```sh /rom/etc/uci-defaults/freifunk-berlin-z90_openvpn```

**Comment by pmelange** [comment]
I have added commit f1d7277853db25c7657ffa455b54c933669483a3 to a new branch.  It addresses the call to /rom/etc/uci-defaults/freifunk-berlin-z90_openvpn.  I am building locally and will report after I've tested.

**Comment by pmelange** [comment]
@SvenRoederer I have finished testing.  The changes in https://github.com/freifunk-berlin/firmware-packages/commit/f1d7277853db25c7657ffa455b54c933669483a3 are important but doesn't solve the issue.

When ```uci commit``` there is an error: ```uci: I/O error```
I tried to remove the file
```
# rm /etc/config/openvpn
rm: can't remove '/etc/config/openvpn': Stale file handle
```

If I edit the file manually, it works.  After, if I try to do rm again, I get the same "Stale file handle" error.

Do you have any ideas?

**Comment by SvenRoederer** [comment]
with https://github.com/freifunk-berlin/firmware-packages/commit/6da0d4e755942aeaf57622a15c1cf554d61541f6 we have a way to work around this problem. 
I'm ok with this solution for hedy-1.0.2. For v1.1.x we should think of a clean solution.

let's close this here.

**Comment by pmelange** [comment]
Yes, let's close this issue and continue the discussion in #641
