### ISSUE TITLE
Create a singe "unified" image of the firmware

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#704]
As discussed at the firmware planning meeting on 12.06.2019 there was
a consensus to have a single unified image which supports the notunnel, tunneldigger, and backbone images.  

see https://pad.freifunk.net/p/berlin-2019

this issue is related to https://github.com/freifunk-berlin/firmware/issues/534, https://github.com/freifunk-berlin/firmware/issues/703

**Comment by SvenRoederer** [comment]
there was already some discussion started in https://github.com/freifunk-berlin/firmware/issues/601, so we should close this and continue there.
