### ISSUE TITLE
How to add a new community

### ISSUE THREAD

**Issue by niccokunzmann** [freifunk-berlin/firmware#729]
I would like to add a community in Bitterfeld-Wolfen.
Here, I will document which steps are taken to add the community profile to the current build.

**Comment by niccokunzmann** [comment]
(I found the community profiles! They were moved. https://github.com/openwrt/luci/issues/2508)
https://github.com/freifunk/openwrt-packages/tree/master/contrib/package/community-profiles/files/etc/config
There, one can create a new community profile.

**Comment by SvenRoederer** [comment]
AS you found the correct repo for your request, I close this.
