### ISSUE TITLE
bbbdigger konfiguriert DNS-Server

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#742]
### Bug report

**What is the problem?**
Beim Aufbau der Verbindung "bbbdigger" wird ein zusätzlicher DNS-Server im System konfiguriert.

```
root@Ahof-frieden-bbbgw:~# cat /tmp/resolv.conf.auto 
# Interface bbbdigger
nameserver 10.36.197.5
search olsr
# Interface wan
nameserver 192.168.9.1
```

**What is the expected behaviour?**
Meiner Meining nach sollte nur ein L2-Link aufgebaut werden, über den dann nur der Mesh- / Tunneltraffic geht und keine weiteren Einstellungen am Node erfolgen.

**Firmware Version:** Freifunk Berlin Development 95ce16e (master branch)

**Site Configuration:** Konfiguration aus Upgrade von Hedy-1.0.x (backbone)

**Comment by pmelange** [comment]
Please write all issues and pull requests in English.

Fixed server side.  Closed

**Comment by SvenRoederer** [comment]
thanks
