### ISSUE TITLE
close all issues relating to Freifunk-Wizard-2

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#746]
As per comment https://github.com/freifunk-berlin/firmware/issues/626#issuecomment-553527201 of @andibraeu there seems nobody working on the new wizard anymore. The last relevant commits to the frontend or backend are several years ago.
So let's close the issues relating to this work.

* https://github.com/freifunk-berlin/firmware/issues/482
* https://github.com/freifunk-berlin/firmware/issues/481
* https://github.com/freifunk-berlin/firmware/issues/397
* https://github.com/freifunk-berlin/firmware/issues/396
* https://github.com/freifunk-berlin/firmware/issues/395
* https://github.com/freifunk-berlin/firmware/issues/394
* https://github.com/freifunk-berlin/firmware/issues/393
* https://github.com/freifunk-berlin/firmware/issues/392

At https://raw.githubusercontent.com/freifunk-berlin/firmware/d92a2c0f48e9a366c510720443f1c3ff540bf0ba/packages/default.txt is a [packages.list](https://github.com/freifunk-berlin/firmware/files/3975791/wizard2-packagelist.txt) that should create a usable image. Last commit of the branch was for such images was d92a2c0f48e9a366c510720443f1c3ff540bf0ba.

@sarumpaet @pmelange @kls0e with the above references you should be able to restart working on this project, if you like.

**Comment by SvenRoederer** [comment]
also to mention @andrenarchy

**Comment by SvenRoederer** [comment]
Also the relating [Milestone](https://github.com/freifunk-berlin/firmware/milestone/6) should be closed.

**Comment by SvenRoederer** [comment]
We should also think of removing the code from the repo, when it's not maintained anymore as it seems to cause confusion (https://github.com/freifunk-berlin/firmware-packages/pull/165)

**Comment by Akira25** [comment]
I agree on the idea to close all issues related to wizard2. But on the other hand, I would like so save this code in any way, in case we decide to continue on that project. Maybe we could push it to another repo of freifunk-berlin?

**Comment by SvenRoederer** [comment]
you can always go back in history and restore it by reverting the commit which deletes the code.

**Comment by xa-y-ax** [comment]
as discussed on 5.5.2020 we close the issues relating to Freifunk-Wizzard-2

**Comment by SvenRoederer** [comment]
wizard2-code was removed from packages-repo and a tag "remove_wizard2" was added for reference.

**Comment by SvenRoederer** [comment]
all relating issues should have been closed now.
