### ISSUE TITLE
upstream-1907: "freifunk-berlin-uplink-tunnelberlin-tunneldigger" cannot be installed

### ISSUE THREAD

**Issue by kls0e** [freifunk-berlin/firmware#756]
Hi, 

this package (new name?) seems to be missing and the corresponding github link 404's: https://github.com/freifunk-berlin/firmware-packages/tree/master/uplinks/freifunk-berlin-uplink-tunnelberlin-tunneldigger-files

**Comment by SvenRoederer** [comment]
Please see: https://github.com/freifunk-berlin/firmware-packages/commit/3e2bd4d8ed82879ad3ba3c5c19c996b5d2516ba0 and https://github.com/freifunk-berlin/firmware-packages/commit/7e33a8783e2d21b710b43e22a141ee774c9b2909

**Comment by SvenRoederer** [comment]
@kls0e is it fixed for you?

**Comment by kls0e** [comment]
it damn sure is by now ;) thanks.
