### ISSUE TITLE
upstream-1907: notunnel_4MB

### ISSUE THREAD

**Issue by kls0e** [freifunk-berlin/firmware#758]
Hi, what would be the contents for the notunnel_4MB.txt and notunnel_4MB.sh packages list files? I know its current content says that images would be too big for 4MB, but I'd still like to try building, especially with ath79-target and maybe removing some other stuff individually.

**Comment by SvenRoederer** [comment]
Isn't ```git revert 5725069daae00b3cc301d70b1be4d9deebb5e8d2```doing the trick?
On console you can use ```git log packages/notunnel_4MB.txt``` to see the list of changes for a specific file. On github you can just click the History-button, in the upper right, then displaying the specific file.

**Comment by SvenRoederer** [comment]
> especially with ath79-target

Before I changed the package-list I did a test-build with ath79-tiny. Regarding removing packages, have also a look into https://github.com/freifunk-berlin/firmware/issues/626

**Comment by kls0e** [comment]
thanks
