### ISSUE TITLE
Mikrotik Image erzeugt Bootschleife

### ISSUE THREAD

**Issue by SvenSFS** [freifunk-berlin/firmware#761]
Hallo,
das aktuelle Image für die Mikrotik Router erzeugt eine Bootschleife.
In Regemässige Abständen Piept das Board und löst einen Reset aus.

Jedenfalls auf einem RouterBOARD 911G-5HPacD

**Comment by SvenRoederer** [comment]
Welche Version hast du genutzt?
Hast du ein Bootlog?
Grad bei ar71xx-mikrotik wichtig: Ist es das richtige Imagefile?

Auch hier wäre die Nutzung der Vorlage hilfreich, denn o.g. fragen werden da automatisch abgefragt.

**Comment by SvenRoederer** [comment]
@SvenSFS  Ist das noch relevant?
