### ISSUE TITLE
buildbot: clicking "Rebuild" gives error "Cannot rebuild: invalid origin"

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#786]
I tried to rebuild a failed build, and the result was "Cannot rebuild: invalid origin"

![Screenshot_2020-04-17_20-55-23](https://user-images.githubusercontent.com/20710446/79604273-10c2e000-80ee-11ea-9acc-0c6c9a0f3066.png)

**Comment by SvenRoederer** [comment]
on page http://buildbot.berlin.freifunk.net/#/builders/2/builds/27 works for me.
Btw. I think this should be reported in the buildbot repo, as it's not firmware related.

**Comment by pmelange** [comment]
Replace issue opened here: https://github.com/freifunk-berlin/buildbot/issues/64
