### ISSUE TITLE
Nodes with unconfigured name keep the template "gib-mir-einen-namen"

### ISSUE THREAD

**Issue by SvenRoederer** [freifunk-berlin/firmware#787]
### Bug report

**What is the problem?**

When the default name of an unconfigured node is not changed in the wizard it stays untouch after finishing the setup.

![template-nodename](https://user-images.githubusercontent.com/1755362/79671386-2e657780-81ca-11ea-97ac-e210be1a698f.png)

**What is the expected behaviour?**
There is code in the wizard which should use a MESH-ipaddress in this case. This seems to be broken.

**Firmware Version:**
Hedy 1.0.2-rc1 / 52c60b6 (I cant tell if there are local modifications, as I collected this data from hopglass only)

**Comment by Akira25** [comment]
As far as I can remember, it worked for me recently on a hedy-1.0.4 device. I will check that for you.

**Comment by Akira25** [comment]
okay, I flashed a GL-AR150 with hedy-1.0.4 (tunneldigger) and gave the wizard only the coordinates, the speed of the internet connection and the okay for the monitor.
Afterwards things worked as i expected: Map, monitor and everything else was fine.

The node does not rename it self after its mesh-address, but after the gateway-address of its DHCP-Network.

![Screenshot_20200419_181345](https://user-images.githubusercontent.com/43141307/79693387-9e2b3f00-826a-11ea-90e3-d6fc437c111c.png)
![Screenshot_20200419_181629](https://user-images.githubusercontent.com/43141307/79693388-9f5c6c00-826a-11ea-895e-92a3d03f170d.png)
![Screenshot_20200419_181946](https://user-images.githubusercontent.com/43141307/79693389-9f5c6c00-826a-11ea-8f14-d22ffb59f386.png)
![Screenshot_20200419_182040](https://user-images.githubusercontent.com/43141307/79693390-a08d9900-826a-11ea-8e73-09fc3f6dabcf.png)

**Comment by SvenRoederer** [comment]
Was also working on a recent "master" build. So unsure, how these node made it onto the map. Probably the node was not configured by the wizard?
I wrote a PM to the nodes contact address to check ... let's see.

**Comment by Akira25** [comment]
I think we should close this issue, as the rest of the problem seems not to be firmware-related (as proven by to poeple).
