### ISSUE TITLE
Enhancement: Use the freifunk favicon.png for the luci interface

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/firmware#791]
I recommend using the freifunk favicon for the web interface. 

![favicon](https://user-images.githubusercontent.com/20710446/80585032-ebe63b00-8a12-11ea-8324-07f544a6591e.png)

To do this, I would recommend putting this into the $OPENWRT_DIR/files/www/luci-static/bootstrap folder to overwrite the original.

![Screenshot_2020-04-29_12-17-33](https://user-images.githubusercontent.com/20710446/80585432-9d856c00-8a13-11ea-9cbf-c9938fd70101.png)

Original size: 733 bytes
Freifunk site:1528 bytes (possibly this can be optimized).

**Comment by Akira25** [comment]
I like that idea. Lets do it.

**Comment by pmelange** [comment]
PR submitted https://github.com/freifunk-berlin/firmware/pull/792

**Comment by SvenRoederer** [comment]
Done by switching to theme "Freifunk-generic" in 02cfecc51c47d82062f350bef96959a605888821
