### ISSUE TITLE
organization: open issue tab in the firmware-packages repo

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#811]
I would love to build freifunk images with openwrt sdk.
I think errors regarding firmware-packages should go into the firmware-packages repository and not in the firmware image builder of freifunk. So we can seperate the firmware builder and the needed freifunk packages. :)

**Comment by SvenRoederer** [comment]
It also feels more natural to me, to have package related issues in the packages-repo. It might save some work (defining tags and releases) to have all issues in one place, but at the end many of these tasks need to be done for the PRs in both repos anyway.

Both ways have advantages and disadvantages. One "Pro" for separating is that new people can more easily see what issue belongs to which repo. 

A similar problem the Gluon-guys had and they decided to keep the core-packages directly in the firmware-repo.
