### ISSUE TITLE
structure: adding valuable information to makefiles

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#812]
Could we maybe add this to our Makefiles?
```
PKG_SOURCE_DATE:=

PKG_LICENSE:=
PKG_LICENSE_FILES:=
```
Further could we maybe add a 
```
PKG_MAINTAINER:=
```
to a Makefile? So we directly know who is responsible for which package?
Maybe we can divide the maintenance between me, @pmelange and @SvenRoederer?

When adding the stuff, we need to care about the ordering. I can do this, if we know what licencse we have, and stuff like this. :)

This is a small change, but it maybe allows so stay more compatible with upstream repository, since they require those things.

**Comment by SvenRoederer** [comment]
not sure if "PKG_MAINTAINER" would make sense, as till now there is no real responsibility. It's always maintained by @freifunk-berlin/firmware-contributors  .

"PKG_LICENSE" we have defined in the firmware-repo. This for sure also applies to the firmware-packages.

"PKG_SOURCE_DATE" please have a look at freifunk-generic-berlin.mk. This defines PKG_VERSION from the git--commit-date, which is in fact the source-date.
