### ISSUE TITLE
luci-app-*: fix all uci permissions

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#818]
With new openwrt versions the luci scripts that use rpcd to call uci are broken. We have to define through `acl.d` the permissions for each app, like I alread did in https://github.com/freifunk-berlin/firmware-packages/pull/206

- https://github.com/freifunk-berlin/firmware/issues/816
- https://github.com/freifunk/openwrt-packages/issues/23

That is for berlin firmware-packages:
- [ ] luci-app-ffwizard-berlin
- [ ] luci-app-owm
- [ ] luci-mod-freifunk-ui

openwrt-packages:
- [ ] luci-mod-freifunk
- [ ] luci-app-freifunk-diagnostics
- [ ] luci-app-freifunk-policyrouting
- [ ]  luci-app-freifunk-widgets 
- [ ] luci-app-meshwizard
- [ ] luci-theme-freifunk-generic

Useful to debug the apps is a code snippet:
```lua
local profile, err = uci:get("freifunk","community","name")
if profile == false then
    luci.util.perror(err)
end
```

**Comment by SvenRoederer** [comment]
Thanks for working this out.
