### ISSUE TITLE
circleci: add circleci from github community package feed

### ISSUE THREAD

**Issue by PolynomialDivision** [freifunk-berlin/firmware#822]
I would like to add the circleci from github package community feed:
https://github.com/openwrt/packages/tree/master/.circleci

**Comment by SvenRoederer** [comment]
For what reason?

**Comment by PolynomialDivision** [comment]
Because we can check if compiling fails, or even produce a ipkg for common architectures so you can directly install it without compiling it by yourself.

**Comment by SvenRoederer** [comment]
* building the packages was done before by the buildbot, before it broke
* this can to some extend solve https://github.com/freifunk-berlin/buildbot/issues/18
