### ISSUE TITLE
output power of wireless devices

### ISSUE THREAD

**Issue by cholin** [freifunk-berlin/firmware#98]
Right now we use 'DE' as country code for wifi-devices. The reg domain setting for DE limits output  power to the following values:

* 2.4GHz: 100 mW
* 5GHz
   * 5150 - 5250: 100 mW
   * 5250 - 5350: 100 mW
   * 5470 - 5725: 500 mW

source: http://git.openwrt.org/?p=14.07/openwrt.git;a=blob;f=package/kernel/mac80211/files/regdb.txt;h=3d1593014aa62caa23114b71c1cd3fa11497103c;hb=HEAD#l255

As mentioned in the regdb.txt these values have been reduced by a factor of 2. If a devices is capable of transmit power control (TPC) we can therefor double the possible output power. For that @stargieg once created a patch (https://github.com/freifunk-berlin/firmware/blob/master/patches/001-package-mac80211-regdb.patch) to alter the world country domain with these values. I would favor to create a new country domain called DE_TPC and put these values there. We could then integrate this in the wizard (would be handy to have a list of capable TPC devices).

What do you think?

**Comment by andrenarchy** [comment]
There'll be no TPC in openwrt/ath9k in the near future. Patching the regd in order to allow higher TX power is discussed in https://github.com/freifunk-berlin/firmware/issues/181#issuecomment-74775447, therefore I'm closing this issue.
